<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;

	if ($formdata == null) {
		
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$name 	= $formdata['name'];
	$email	= $formdata['email'];
	$comment= $formdata['comment'];
	
	
	$arrInput = array(
					array('label'=>'Họ và tên','input'=>$name,'style'=>'font-size: 15pt;'),
					array('label'=>'Email','input'=>$email),
					array('label'=>'Lời bình luận','input'=>$comment),
					
	);
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-gallery/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-gallery/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>