<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-services-delete-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}
	
	$service_title 	= $this->cmsReplaceString($this->Item['service_title']);
	$cover_image = FILES_URL . '/services/cover-images/medium/' . $this->Item['cover_image'];
	$cover_image = '<img src="' . $cover_image . '"/>';
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-service/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-service/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors" class="alert alert-danger">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row" class="row">
					<div class="col-lg-2"><?php echo $this->translate('admin-services-add-label-servicetitle'); ?></div>
					<div class="col-lg-4"><?php echo $cover_image; ?></div>
					<div class="col-lg-6"><span style="font-size: 15pt;"><?php echo $service_title; ?></span></div>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>