<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-services-edit-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['service_title'] = '';
		$formdata['service_brief'] = '';
		$formdata['service_content'] = '';
		$formdata['price'] = 'Liên hệ';
		$formdata['cover_image'] = '';
		$formdata['lock_status'] = 1;
		$formdata['publish'] = 1;
		$formdata['order'] = $this->lastServiceOrder + 1;
		$formdata['featured_service'] = 0;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}

	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['service_title'] = '';
		$formstyle['service_brief'] = '';
		$formstyle['service_content'] = '';
		$formstyle['price'] = '';
		$formstyle['cover_image'] = 'width: 300px;';
		$formstyle['order'] = '';
	}	
	
	//----- CREATE: SERVICE CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbServiceCat;
	$slbServiceCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),array('name'=>'category_id','value'=>$formdata['category_id']));
	
	$service_title 	= $this->formText('service_title',$formdata['service_title'],array('class'=>'form-control','style'=>$formstyle['service_title']));
	$service_brief 	= $this->formText('service_brief',$formdata['service_brief'],array('class'=>'form-control','style'=>$formstyle['service_brief']));
	$service_content = $this->cmsEditor('service_content',$formdata['service_content'],array('toolbar'=>'FullToolbar'),array('style'=>'margin-left: 175px;'));
	$service_price 	= $this->formText('price',$formdata['price'],array('class'=>'txtlong','style'=>$formstyle['price']));
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-service_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->Item['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-services-add-publish-warning') . $this->formHidden('publish',0);
	}
	//----- CREATE: featured service option --------------------------
	if (in_array('admin_admin-service_change-featured-service', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-no'),$this->translate('admin-cw-yes'));
		if (!isset($formdata['featured_service'])) {
			$this->Item['featured_service'] = 0;
		}
		$featured_service = $this->formRadio('featured_service',$formdata['featured_service'],null,$options, ' ');
	} else {
		$featured_service = $this->translate('admin-services-add-featured-warning') . $this->formHidden('featured_service',0);
	}
	//----- CREATE: lock status option --------------------------
	if (in_array('admin_admin-service_change-lock-status', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->Item['lock_status'] = 0;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-services-add-lockstatus-warning') . $this->formHidden('lock_status',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	
	
	//----- CREATE: cover image option --------------------------
	$imageSize = $this->imageSize('production','service_cover_image_large');
	$strRecommendSize = '<br/> (recommend image size: ' .$imageSize['width'] .'px-' .$imageSize['height'] .'px)';
	if (!empty($formdata['cover_image'])) {
		$cover_image 	= FILES_URL . '/services/cover-images/small/' . $formdata['cover_image'];
		$cover_image	= '<img src="' . $cover_image .'"/><br/>';
		$current_cover_image = $this->formHidden('current_cover_image',$formdata['cover_image']);
	} else {
		$cover_image	= FILES_URL . '/services/cover-images/small/' . $formdata['current_cover_image'];
		$cover_image	= '<img src="' . $cover_image .'"/><br/>';
		$current_cover_image = $this->formHidden('current_cover_image',$formdata['current_cover_image']);
	}
	$cover_image   .= $this->formFile('cover_image',array('style'=>'')) . $this->translate('admin-cp-uploadnewcoverimage')
										.$strRecommendSize .$current_cover_image;
	
	$arrInput = array(
					array('label'=>$this->translate('admin-services-add-label-servicecategory'),'input'=>$slbServiceCat),
					array('label'=>$this->translate('admin-services-add-label-servicetitle'),'input'=>$service_title),
					array('label'=>$this->translate('admin-services-add-label-servicebrief'),'input'=>$service_brief),
					array('label'=>$this->translate('admin-services-add-label-servicecontent'),'input'=>$service_content),
					array('label'=>$this->translate('admin-services-add-label-serviceprice'),'input'=>$service_price),
					array('label'=>$this->translate('admin-services-add-label-coverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-services-add-label-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-services-add-label-featuredservice'),'input'=>$featured_service),
					array('label'=>$this->translate('admin-services-add-label-lockstatus'),'input'=>$lock_status),		
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-service/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-service/sublink/index.php'); ?>

	<?php
		if(!empty($errors)) {
	?>
		<div class="alert alert-danger"><?php echo $errors; ?></div>
	<?php 
		}
	?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>