<?php
	//----- Lay du lieu thong tin service truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin service
	$formdata = $this->Item;

	if ($formdata == null) {
		$formdata['category_id'] = 0;
		$formdata['category_name'] = '';
		$formdata['service_title'] = '';
		$formdata['service_brief'] = '';
		$formdata['service_content'] = '';
		$formdata['cover_image'] = '';
		$formdata['lock_status'] = 1;
		$formdata['publish'] = 1;
		$formdata['order'] = $this->lastServiceOrder + 1;
		$formdata['featured_service'] = 0;
		$formdata['created_id'] = 0;
		$formdata['created_name'] = '';
		$formdata['created_time'] = '0000-00-00 00:00:00';
		$formdata['last_modified_id'] = 0;
		$formdata['last_modified_name'] = '';
		$formdata['last_modified_time'] = '0000-00-00 00:00:00';
		$formdata['publisher_id'] = 0;
		$formdata['publisher_name'] = '';
		$formdata['publish_time'] = '0000-00-00 00:00:00';
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$linkServiceCat	= $this->baseUrl('/admin/admin-service-category/info/id/' .$formdata['category_id']);
	$category_name		= '<a href="' . $linkServiceCat . '">' . $formdata['category_name'] . '</a>';
	
	$service_title 	= $formdata['service_title'];
	$service_brief 	= $formdata['service_brief'];
	$service_content = $formdata['service_content'];
	//----- thong tin public
	$publish		= $formdata['publish'];
	if ($publish == 0) {
		$publish = $this->translate('admin-cw-nopublish');
	} else {
		$publish = $this->translate('admin-cw-publish');
	}
	//----- thong tin featured service
	$featured_service	= $formdata['featured_service'];
	if ($featured_service == 0) {
		$featured_service = $this->translate('admin-cw-no');
	} else {
		$featured_service = $this->translate('admin-cw-yes');
	}
	//----- thong tin lock status
	$lock_status	= $formdata['lock_status'];
	if ($lock_status == 0) {
		$lock_status = $this->translate('admin-cw-unlock');
	} else {
		$lock_status = $this->translate('admin-cw-lock');
	}
	
	$order 	= $formdata['order'];
	
	//----- CREATE: cover image option --------------------------
	$cover_image 	= FILES_URL . '/services/cover-images/small/' . $formdata['cover_image'];
	$cover_image	= '<img src="' . $cover_image .'"/><br/>';
	
	//----- thong tin nguoi tao, ngay gio tao
	$created_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['created_id']) . '">' . $formdata['created_name'] . '</a>';
	$created_time	= date('d/m/Y H:i:s',strtotime($formdata['created_time']));
	
	//----- thong tin nguoi, ngay, gio chinh sua cuoi cung
	if ($formdata['last_modified_id'] != 0) {
		$last_modified_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['last_modified_id']) . '">' . $formdata['last_modified_name'] . '</a>';
		$last_modified_time	= date('d/m/Y H:i:s',strtotime($formdata['last_modified_time']));
	} else {
		$last_modified_name	= '';
		$last_modified_time	= '';
	}
	
	
	//----- thong tin nguoi publish, ngay gio publish
	if ($formdata['publisher_id'] != 0) {
		$publisher_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['publisher_id']) . '">' . $formdata['publisher_name'] . '</a>';
		$publish_time	= date('d/m/Y H:i:s',strtotime($formdata['publish_time']));
	} else {
		$publisher_name	= '';
		$publish_time	= '';
	}
	
	
	$arrInput = array(
					array('label'=>$this->translate('admin-services-add-label-servicecategory'),'input'=>$category_name),
					array('label'=>$this->translate('admin-services-add-label-servicetitle'),'input'=>$service_title),
					array('label'=>$this->translate('admin-services-add-label-servicebrief'),'input'=>$service_brief),
					array('label'=>$this->translate('admin-services-add-label-servicecontent'),'input'=>$service_content),
					array('label'=>$this->translate('admin-services-add-label-coverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-services-add-label-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-services-add-label-featuredservice'),'input'=>$featured_service),
					array('label'=>$this->translate('admin-services-add-label-lockstatus'),'input'=>$lock_status),
					array('label'=>$this->translate('admin-cp-createdby'),'input'=>$created_name),
					array('label'=>$this->translate('admin-cp-createdtime'),'input'=>$created_time),
					array('label'=>$this->translate('admin-cp-lastmodifiedby'),'input'=>$last_modified_name),
					array('label'=>$this->translate('admin-cp-lastmodifiedtime'),'input'=>$last_modified_time),
					array('label'=>$this->translate('admin-cp-publishedby'),'input'=>$publisher_name),
					array('label'=>$this->translate('admin-cp-publishedtime'),'input'=>$publish_time),
			);
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-service/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-service/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>