<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['category_id'] = 0;
		$formdata['article_title'] = '';
		$formdata['article_brief'] = '';
		$formdata['article_content'] = '';
		$formdata['cover_image'] = '';
		$formdata['publish'] = 0;
		$formdata['lock_status'] = 1;
		$formdata['order'] = $this->lastArticleOrder + 1;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['article_title'] = '';
		$formstyle['article_brief'] = '';
		$formstyle['article_content'] = '';
		$formstyle['category_id'] = 'min-width: 200px';
		$formstyle['cover_image'] = '';
		$formstyle['order'] = '';
	}
	//----- CREATE: NEWS CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbNewsCat;
	$slbNewsCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),array('name'=>'category_id[]',
						'style'=>$formstyle['category_id'],'value'=>$formdata['category_id'],'size'=>5,'multiple'=>true));
	
	$article_title 	= $this->formText('article_title',$formdata['article_title'],array('class'=>'form-control','style'=>$formstyle['article_title']));
	$article_brief 	= $this->formText('article_brief',$formdata['article_brief'],array('class'=>'form-control','style'=>$formstyle['article_brief']));
	$article_content = $this->cmsEditor('article_content',$formdata['article_content'],array('toolbar'=>'FullToolbar'),array('class'=>'form-control'));
	$imageSize = $this->imageSize('production','news_cover_image_medium');
	$strRecommendSize = ' (recommend image size: ' .$imageSize['width'] .'px-' .$imageSize['height'] .'px)';
	$cover_image 	= $this->formFile('cover_image',array('style'=>$formstyle['cover_image'])) .$strRecommendSize;
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-news-article_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->Item['publish'] = 0;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-newsarticle-add-warning-publish') . $this->formHidden('publish',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	
	//----- CREATE: lock option ---------------------
	//----- lay du lieu cap phep cua nguoi dung login de xac dinh nguoi dung nay
	//----- co quyen lock/unlock page hay khong
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-news-article_change-lock-status', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->FormData['lock_status'] = 1;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-newsarticle-add-warning-publish') . $this->formHidden('lock_status',0);
	}
	
	$arrInput = array(
					array('label'=>$this->translate('admin-newsarticle-add-label-newscategory'),'input'=>$slbNewsCat),
					array('label'=>$this->translate('admin-newsarticle-add-label-newstitle'),'input'=>$article_title),
					array('label'=>$this->translate('admin-newsarticle-add-label-newsbrief'),'input'=>$article_brief),
					array('label'=>$this->translate('admin-newsarticle-add-label-newscontent'),'input'=>$article_content),
					array('label'=>$this->translate('admin-newsarticle-add-label-newscoverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-newsarticle-add-label-newspublish'),'input'=>$publish),
					array('label'=>$this->translate('admin-newsarticle-add-label-lockstatus'),'input'=>$lock_status),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-news-article/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-news-article/sublink/index.php'); ?>

	<?php
		if(!empty($errors)) {
	?>
		<div class="alert alert-danger"><?php echo $errors; ?></div>
	<?php 
		}
	?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>