<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-newsarticle-delete-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}

	$article_title 	= $this->cmsReplaceString($this->Item['article_title']);
	$cover_image = FILES_URL . '/news/cover-images/small/' . $this->Item['cover_image'];
	$cover_image = '<img src="' . $cover_image . '"/>';
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-news-article/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-news-article/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors" class="alert alert-danger">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row">
					<div class="col-lg-2">
						<strong><?php echo $this->translate('admin-newsarticle-col-artitletitle'); ?></strong>
					</div>
					<div class="col-lg-2">
						<?php echo $cover_image; ?>
					</div>
					<div class="col-lg-8">
						<?php echo $article_title; ?>
					</div>
				</div>
		
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>