<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblArticleTitle = $this->cmsSortLink('na.article_title',$this->arrParam,$this->translate('admin-newsarticle-col-artitletitle'),$this->imgUrl,$action_link);
	$lblArticleCoverImage = $this->translate('admin-cp-cover-image');
	$lblArticleCategory = $this->translate('admin-newscategory-col-articlecategory');
	$lblArticlePublish = $this->cmsSortLink('na.publish',$this->arrParam,$this->translate('admin-cw-publish'),$this->imgUrl,$action_link);
	$lblArticlePublishTime = $this->cmsSortLink('na.publish_time',$this->arrParam,$this->translate('admin-newscategory-col-publishtime'),$this->imgUrl,$action_link);
	$lblArticleViewCounter = $this->cmsSortLink('na.view_counter',$this->arrParam,$this->translate('admin-newscategory-col-viewcounter'),$this->imgUrl,$action_link);
	$lblArticleID = $this->cmsSortLink('na.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblArticleOrder = $this->cmsSortLink('na.order',$this->arrParam,$this->translate('admin-cw-order'),$this->imgUrl,$action_link);
	$lblArticleLockStatus = $this->cmsSortLink('na.lock_status',$this->arrParam,$this->translate('admin-cp-lockstatus'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: NEWS CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbNewsCat;
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/newscategory');
	$slbNewsCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),
			array('name'=>'category_id','onChange'=>"OnSubmitForm('" .$linkSearch ."')","value"=>$ssFilter['category_id']));
	$selectGroup = 'News Category: ' .$slbNewsCat;
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-news-article/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-news-article/sublink/index.php'); ?>
	
	<!-- ------------------------------------ table Admin verion 2 ------------------------- -->
	<div class="panel panel-default adminlist">
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover" id="dataTables-object">
					<thead>
						<tr>
							<th class="cid">
								<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
							</th>
							<th><?php echo $this->translate('admin-newsarticle-col-artitletitle'); ?></th>
							<th class="col_coverimage"><?php echo $this->translate('admin-cp-cover-image'); ?></th>
							<th class="col_article_category"><?php echo $this->translate('admin-newscategory-col-articlecategory'); ?></th>
							<th class="col_view_counter"><?php echo $this->translate('admin-newscategory-col-viewcounter'); ?></th>
							<th class="col_order"><?php echo $this->translate('admin-cw-order'); ?></th>
							<th class="col_publish"><?php echo $this->translate('admin-cw-publish'); ?></th>
							<th class="col_publish_time"><?php echo $this->translate('admin-newscategory-col-publishtime'); ?></th>
							<th class="col_control">Control</th>
							<th class="col_lock_status"><?php echo $this->translate('admin-cp-lockstatus'); ?></th>
						</tr>
					</thead>
					<tbody>
                                    
					<?php 
						foreach ($this->Items as $key => $value) {
							$value = $this->cmsReplaceString($value);
							$id = $value['id'];
							$article_title = $value['article_title'];
							$cover_image = FILES_URL . '/news/cover-images/small/' . $value['cover_image'];
							$cover_image = '<img src="' . $cover_image . '"/>';
							$publish = $value['publish'];
							if ($publish == 1) {
								$linkPublish = $this->baseUrl($this->currentController .'/publish/type/inactive/id/' .$id);
								$publish = $this->cmsIconButton('Stop Publish this article','fa fa-hover fa-check',$linkPublish,'css');
							} else {
								$linkPublish = $this->baseUrl($this->currentController .'/publish/type/active/id/' .$id);
								$publish = $this->cmsIconButton('Publish this article','fa fa-hover fa-minus-circle',$linkPublish,'css');
							}
							//----- chuyen publish_time tu dang Y-m-d sang d-m-Y de hien thi ra view
							$publish_time = date('d/m/Y H:i:s',strtotime($value['publish_time']));
		
							//----- neu doi tuong bi khoa thi vo hieu hoa o textbox order
							if ($value['lock_status'] == 0) {
								$order = $this->formText('order[' .$value['id'] .']',$value['order'],
										array('style'=> 'width: 30px; text-align: center;'));
							} else if ($value['lock_status'] == 1) {
								$order = $this->formText('order[' .$value['id'] .']',$value['order'],
										array('style'=> 'width: 30px; text-align: center;','disabled'=>true));
							}
							
							$lock_status = $value['lock_status'];
							if ($lock_status == 1) {
								$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/inactive/id/' .$id);
								$lock_status = $this->cmsIconButton('This page is locked','fa fa-hover fa-lock',$linkLockStatus,'css');
							} else {
								$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/active/id/' .$id);
								$lock_status = $this->cmsIconButton('This page is unlocked','fa fa-hover fa-unlock',$linkLockStatus,'css');
							}
							$view_counter = $value['view_counter'];				
							$articleCategory = $value['articleCategory'];
							$strArticleCategory = '';
							if (count($articleCategory) > 0) {
								foreach	($articleCategory as $key2=>$value2) {
									$category_id = $value2['category_id'];
									$categoryLink = $this->baseUrl('/admin/admin-news-category/info/id/' . $category_id);
									$category_name = $value2['category_name'];
									$strArticleCategory .= '<a href="' . $categoryLink . '">' . $category_name . '</a><br/>';
								}
							}
							
							$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
							$btnInfo = $this->cmsIconButton('View information','fa fa-info-circle fa-lg',$linkInfo,'css');
							$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
							$btnEdit = $this->cmsIconButton('Edit Item','fa fa-edit fa-lg',$linkEdit,'css');
							$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
							$btnDelete = $this->cmsIconButton('Delete Item','fa fa-times-circle fa-lg',$linkDelete,'css');
							$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
							
							$cid = $this->formCheckbox('cid[]',$value['id']);
					?>
					
					<tr class="odd gradeX even">						
						<td align="center"><?php echo $cid; ?></td>
						<td align="left"><?php echo $article_title; ?></td>
						<td align="center"><?php echo $cover_image; ?></td>
						<td align="center"><?php echo $strArticleCategory; ?></td>
						<td align="center"><?php echo $view_counter; ?></td>
						<td align="center"><?php echo $order; ?></td>
						<td align="center"><?php echo $publish; ?></td>
						<td align="center"><?php echo $publish_time; ?></td>
						<td align="center">
							<?php echo $strControlIconButton; ?>
						</td>
						<td align="center"><?php echo $lock_status; ?></td>
					</tr>
			
                <?php 
				} // ------------- dong vong lap foreach ----------------
			?>                    
                                        
					</tbody>
				</table>
			</div> <!-- /.table-responsive -->
		</div> <!-- /.panel-body -->
	</div>
	<!-- -------------------------------- End table Admin verion 2 ------------------------- -->
	
</form>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-object').dataTable();
    });
</script>