<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['gallery_id'] = 0;
		$formdata['image_title'] = '';
		$formdata['gallery_image'] = '';
		$formdata['publish'] = 1;
		$formdata['order'] = $this->lastImageOrder + 1;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['gallery_id'] = 'min-width: 200px';
		$formstyle['image_title'] = '';
		$formstyle['gallery_image'] = '';
		$formstyle['order'] = '';
	}
	//----- CREATE: GALLERY SELECT BOX --------------------------
	$options = $this->slbGallery;
	$slbGallery = $this->formSelect('gallery_id',$formdata['gallery_id'],array('style'=>$formstyle['gallery_id']),$options);
	
	$image_title 	= $this->formText('image_title',$formdata['image_title'],array('class'=>'txtlong','style'=>$formstyle['image_title']));
	$gallery_image 	= $this->formFile('gallery_image',array('style'=>$formstyle['gallery_image'])) .' (recommend image size: 613px-340px)';
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-gallery-image_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->FormData['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-galleryimage-add-publish-warning') . $this->formHidden('publish',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));

	$arrInput = array(
					array('label'=>$this->translate('admin-galleryimage-add-label-imagegallery'),'input'=>$slbGallery),
					array('label'=>$this->translate('admin-galleryimage-add-label-imagetitle'),'input'=>$image_title),
					array('label'=>$this->translate('admin-product-add-label-coverimage'),'input'=>$gallery_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-product-add-label-publish'),'input'=>$publish),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-product/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-product/sublink/index.php'); ?>

	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>