<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-product-edit-lockstatus-warning');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}
	
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['product_category_id'] = 0;
		$formdata['product_name'] = '';
		$formdata['product_serial'] = '';
		$formdata['price'] = '';
		$formdata['product_detail'] = '';
		$formdata['cover_image'] = '';
		$formdata['publish'] = 0;
		$formdata['lock_status'] = 0;
		$formdata['order'] = 0;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}

	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['product_name'] = '';
		$formstyle['product_serial'] = '';
		$formstyle['price'] = '';
		$formstyle['product_detail'] = '';
		$formstyle['product_category_id'] = 'min-width: 200px';
		$formstyle['cover_image'] = '';
		$formstyle['order'] = '';
	}	
	
	//----- CREATE: PRODUCT CATEGORY SELECT BOX --------------------------
	$options = $this->slbProCat;
	$slbProCat = $this->formSelect('product_category_id',$formdata['product_category_id'],array('style'=>$formstyle['product_category_id']),$options);
	
	$product_name 	= $this->formText('product_name',$formdata['product_name'],array('class'=>'txtlong','style'=>$formstyle['product_name']));
	$product_serial	= $this->formText('product_serial',$formdata['product_serial'],array('class'=>'txtshort','style'=>$formstyle['product_serial']));
	$price		 	= $this->formText('price',$formdata['price'],array('class'=>'txtshort','style'=>$formstyle['price']));
	$product_detail = $this->cmsEditor('product_detail',$formdata['product_detail'],array('toolbar'=>'FullToolbar'),array('style'=>'margin-left: 175px;'));
	
	//----- CREATE: cover image option --------------------------
	if (!empty($formdata['cover_image'])) {
		$cover_image 	= FILES_URL . '/products/cover-images/small/' . $formdata['cover_image'];
		$cover_image	= '<img src="' . $cover_image .'"/><br/>';
		$current_cover_image = $this->formHidden('current_cover_image',$formdata['cover_image']);
	} else {
		$cover_image	= FILES_URL . '/products/cover-images/small/' . $formdata['current_cover_image'];
		$cover_image	= '<img src="' . $cover_image .'"/><br/>';
		$current_cover_image = $this->formHidden('current_cover_image',$formdata['current_cover_image']);
	}
	$cover_image   .= $this->formFile('cover_image',array('style'=>'')) . $this->translate('admin-cp-uploadnewcoverimage')
					.'<br/>(recommend image size: 613px-340px)' . $current_cover_image;
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-gallery-image_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->FormData['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-product-add-publish-warning') . $this->formHidden('publish',0);
	}
	
	//----- CREATE: lock status option --------------------------
	if (in_array('admin_admin-product_change-lock-status', $arrAcl)) {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->FormData['lock_status'] = 0;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-product-add-lockstatus-warning') . $this->formHidden('lock_status',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	
	$arrInput = array(
			array('label'=>$this->translate('admin-product-add-label-categoryname'),'input'=>$slbProCat),
			array('label'=>$this->translate('admin-product-add-label-productname'),'input'=>$product_name),
			array('label'=>$this->translate('admin-product-add-label-productserial'),'input'=>$product_serial),
			array('label'=>$this->translate('admin-product-add-label-price'),'input'=>$price),
			array('label'=>$this->translate('admin-product-add-label-productdetail'),'input'=>$product_detail,'style'=>'margin-left: 175px;'),
			array('label'=>$this->translate('admin-product-add-label-coverimage'),'input'=>$cover_image,'style'=>'margin-left: 175px;'),
			array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
			array('label'=>$this->translate('admin-product-add-label-publish'),'input'=>$publish),
			array('label'=>$this->translate('admin-product-add-label-lockstatus'),'input'=>$lock_status),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-product/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-product/sublink/index.php'); ?>

	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>