<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['gallery_name'] = '';
		$formdata['description'] = '';
		$formdata['cover_image'] = '';
		$formdata['publish'] = 1;
		$formdata['lock_status'] = 1;
		$formdata['order'] = $this->lastGalleryOrder + 1;
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['gallery_name'] = '';
		$formstyle['cover_image'] = 'width: 300px;';
		$formstyle['order'] = '';
	}
	
	$gallery_name 	= $this->formText('gallery_name',$formdata['gallery_name'],array('class'=>'txtlong','style'=>$formstyle['gallery_name']));
	$description	= $this->formText('description',$formdata['description'],array('class'=>'txtlong'));
	$cover_image 	= $this->formFile('cover_image',array('style'=>$formstyle['cover_image']));
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	$arrAcl = $info->acl['privileges'];
	if (in_array('admin_admin-gallery_publish', $arrAcl)) {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->FormData['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-gallery-add-publish-warning') . $this->formHidden('publish',0);
	}
	
	//----- CREATE: lock status option --------------------------
	if (in_array('admin_admin-gallery_change-lock-status', $arrAcl)) {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->FormData['lock_status'] = 0;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-gallery-add-lockstatus-warning') . $this->formHidden('lock_status',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));

	$arrInput = array(
					array('label'=>$this->translate('admin-gallery-add-label-galleryname'),'input'=>$gallery_name),
					array('label'=>$this->translate('admin-gallery-add-label-description'),'input'=>$description),
					array('label'=>$this->translate('admin-gallery-add-label-coverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-gallery-add-label-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-gallery-add-label-lockstatus'),'input'=>$lock_status),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-gallery/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-gallery/sublink/index.php'); ?>

	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>