<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['image_link'] = '';
	}
	
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['imageupload'] = '';
		$formstyle['image_link'] = '';
	}

	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	
	$lblAdvertImage = $this->translate('admin-template-advertise-image-new');
	$lblImageLink	= $this->translate('admin-template-advertise-image-link');
	
	$imageSize = $this->imageSize('production','homepageAdvertiseImage');
	$strRecommendSize = ' (recommend image size: ' .$imageSize['width'] .'px-' .$imageSize['height'] .'px)';
	
	$banner_image 	= $this->formFile('imageupload',array('style'=>$formstyle['imageupload'])) .$strRecommendSize;
	
	$image_link 	= $this->formText('image_link',$formdata['image_link'],array('class'=>'txtlong','style'=>$formstyle['image_link']));
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	$arrInput = array(
			array('label'=>$this->translate('admin-template-advertise-image-new'),'input'=>$banner_image),
			array('label'=>$this->translate('admin-template-advertise-image-link'),'input'=>$image_link),
	);
	
	//----- lay danh sach cac file anh co trong thu muc templates/banner-slide
	$dir = new DirectoryIterator(FILES_PATH . '/templates/advertise-images/');
	$arrAdvertImages = array();
	foreach ($dir as $fileInfo) {
		if (!$fileInfo->isDot()) {
			$arrAdvertImages[] = $fileInfo->getFilename();
		}
	}
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-template/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-template/sublink/index.php'); ?>
	
	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX ----------------------------------->

		<div id="filters">
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
			</div>
			<div class="clr"></div>
		</div>
		
		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		<table class="adminlist">
			<thead>
				
				<tr>
					<th><?php echo $lblAdvertImage; ?></th>
					<th><?php echo $lblImageLink; ?></th>
					<th width="90">Control</th>
				</tr>
			</thead>
				<?php
					if (count($arrAdvertImages) > 0) {
						foreach ($arrAdvertImages as $key=>$val) {
							$image_name = $val;
							$image_url = '<img src="' . FILES_URL . '/templates/advertise-images/' . $image_name .'"/>' ;
							
							$objIni = new Zendvn_System_Ini();
							$filepath = APPLICATION_PATH . '/configs/image-list.ini';
							$imageList = $objIni->readIni($filepath);
							$homepageAdvertiseImage = $imageList['production']['homepageAdvertiseImage'];
							
							$image_link = '';
							foreach ($homepageAdvertiseImage as $key=>$value) {
								if ($value['name'] == $image_name) {
									$image_link = $value['link'];
								}
							}
							
							
							$linkEdit = $this->baseUrl($this->currentController . '/advertise-edit/image/' .$image_name);
							$btnEdit = $this->cmsIconButton('Edit Item',$this->imgUrl .'/icon/icon_edit.png',$linkEdit);
							
							$linkDelete = $this->baseUrl($this->currentController . '/advertise-delete/image/' . $image_name);
							$btnDelete = $this->cmsIconButton('Delete Item',$this->imgUrl .'/icon/icon_del.png',$linkDelete);
							
							$strControlIconButton = $btnEdit . ' ' . $btnDelete;
				?>
				
				<tr class="even">
					<td align="left"><?php echo $image_url; ?></td>
					<td align="left"><a href="<?php echo $image_link; ?>"><?php echo $image_link; ?></a></td>
					<td align="center" >
						<span><?php echo $btnEdit; ?></span>
						<span onclick="return confirm('Bạn có chắc chắn xóa ảnh này?')"><?php echo $btnDelete; ?></span>
					</td>
				</tr>
				
				<?php
						}
					}
				?>
			
		</table>
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>