<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['imageupload'] = '';
	}

	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	//----- lay danh sach cac file anh co trong thu muc templates/banner-slide
	$dir = new DirectoryIterator(FILES_PATH . '/templates/company-map/');
	$arrImages = array();
	foreach ($dir as $fileInfo) {
		if (!$fileInfo->isDot()) {
			$arrImages[] = $fileInfo->getFilename();
		}
	}
	$image_name = $arrImages[0];
	$image_url = '<img src="' . FILES_URL . '/templates/company-map/' . $image_name .'"/>' ;
	$lblMapImage = $this->translate('admin-template-companymap-image');
	$map_image 	= $this->formFile('imageupload',array('style'=>$formstyle['imageupload'])) . '(370px - 307px)';
	
	$arrInput = array(
			array('label'=>$this->translate('admin-template-map-image'),'input'=>$image_url),
			array('label'=>$this->translate('admin-template-map-image-new'),'input'=>$map_image),
	);
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-template/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-template/sublink/index.php'); ?>
	
	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX ----------------------------------->

		<div id="filters">
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
			</div>
			<div class="clr"></div>
		</div>
		
		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>