<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['document_name'] = '';
		$formdata['document_filename'] = '';
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['document_name'] = '';
	}

	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	$document_name = $formdata['document_name'];
			
	$document_path = FILES_URL . '/documents/' .$formdata['document_filename'];
	$document_link = '<a href="' .$document_path .'">' .$formdata['document_filename'] .'</a>';
	$document_filename = $this->formHidden('document_filename',$formdata['document_filename']) .$document_link;
	$document_name = $this->formText('document_name',$formdata['document_name'],array('class'=>'txtlong','style'=>$formstyle['document_name']));
	
	$arrInput = array(
			array('label'=>$this->translate('admin-template-documents-new'),'input'=>$document_filename),
			array('label'=>$this->translate('admin-template-documents-name'),'input'=>$document_name),
	);
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-template/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-template/sublink/index.php'); ?>
	
	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX ----------------------------------->

		<div id="filters">
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
			</div>
			<div class="clr"></div>
		</div>
		
		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>