<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['document_name'] = '';
	}
	
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['document_file'] = '';
		$formstyle['document_name'] = '';
	}

	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	
	$lblDocument = $this->translate('admin-template-documents-new');
	$lblDocumentName = $this->translate('admin-template-documents-name');
	
	$document_file 	= $this->formFile('document_file',array('style'=>$formstyle['document_file']));
	
	$document_name 	= $this->formText('document_name',$formdata['document_name'],array('class'=>'txtlong','style'=>$formstyle['document_name']));
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	$arrInput = array(
			array('label'=>$this->translate('admin-template-documents-new'),'input'=>$document_file),
			array('label'=>$this->translate('admin-template-documents-name'),'input'=>$document_name),
	);
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-template/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-template/sublink/index.php'); ?>
	
	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX ----------------------------------->

		<div id="filters">
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
			</div>
			<div class="clr"></div>
		</div>
		
		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		<table class="adminlist">
			<thead>
				
				<tr>
					<th><?php echo $lblDocument; ?></th>
					<th><?php echo $lblDocumentName; ?></th>
					<th width="90">Control</th>
				</tr>
			</thead>
				
				<?php
					//----- doc file /application/configs/file-list.ini lay danh sach cac file
					//----- trong section [documents] hien thi ra o day
					$documentList = $this->documentList;
					if (count($documentList) > 0) {
						foreach ($documentList as $key=>$val) {
							$document_name = $val['name'];
							$document_filename = $val['filename'];
							$document_path = FILES_URL . '/documents/' . $document_filename;
							
							$linkEdit = $this->baseUrl($this->currentController . '/documents-edit/document-file/' .$document_filename);
							$btnEdit = $this->cmsIconButton('Edit Item',$this->imgUrl .'/icon/icon_edit.png',$linkEdit);
							
							$linkDelete = $this->baseUrl($this->currentController . '/documents-delete/document-file/' . $document_filename);
							$btnDelete = $this->cmsIconButton('Delete Item',$this->imgUrl .'/icon/icon_del.png',$linkDelete);
							
							$strControlIconButton = $btnEdit . ' ' . $btnDelete;
				?>
				
				<tr class="even">
					<td align="left"><a href="<?php echo $document_path; ?>"><?php echo $document_filename; ?></a></td>
					<td align="left"><?php echo $document_name; ?></td>
					<td align="center" >
						<span><?php echo $btnEdit; ?></span>
						<span onclick="return confirm('Bạn có chắc chắn xóa tài liệu này?')"><?php echo $btnDelete; ?></span>
					</td>
				</tr>
				
				<?php
						}
					}
				?>
			
		</table>
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>