<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	
	$lblGalleryName = $this->cmsSortLink('g.gallery_name',$this->arrParam,$this->translate('admin-gallery-add-label-galleryname'),$this->imgUrl,$action_link);
	$lblProductCoverImage = $this->translate('admin-cp-cover-image');
	
	$lblGalleryPublish = $this->cmsSortLink('g.publish',$this->arrParam,$this->translate('admin-cw-publish'),$this->imgUrl,$action_link);
	$lblGalleryPublishTime = $this->cmsSortLink('g.publish_time',$this->arrParam,$this->translate('admin-cp-publishtime'),$this->imgUrl,$action_link);
	
	$lblGalleryOrder = $this->cmsSortLink('g.order',$this->arrParam,$this->translate('admin-cw-order'),$this->imgUrl,$action_link);
	
	$lblGalleryID = $this->cmsSortLink('g.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblGalleryLockStatus = $this->cmsSortLink('g.lock_status',$this->arrParam,$this->translate('admin-cp-lockstatus'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-gallery/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-gallery/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX ----------------------------------->
			<div id="filters">
				<div style="float: left">
					<?php echo $strSearch; ?>
				</div>
				<div class="clear"></div>
			</div>

		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		<table class="adminlist">
			<thead>
				<tr>
					<th width="43" >
						<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
					</th>
					<th><?php echo $lblGalleryName; ?></th>
					<th><?php echo $lblProductCoverImage; ?></th>
					<th width="89"><?php echo $lblGalleryPublish; ?></th>
					<th><?php echo $lblGalleryPublishTime; ?></th>
					<th><?php echo $lblGalleryOrder; ?></th>
					<th width="90">Control</th>
					<th width="34"><?php echo $lblGalleryID; ?></th>
					<th><?php echo $lblGalleryLockStatus; ?></th>
				</tr>
			</thead>
			
			<?php 
				foreach ($this->Items as $key => $value) {
					$id = $value['id'];
					$gallery_name = $value['gallery_name'];
					$cover_image = FILES_URL . '/gallery/cover-images/small/' . $value['cover_image'];
					$cover_image = '<img src="' . $cover_image . '"/>';
					//----- lay thong so publish
					$publish = $value['publish'];
					if ($publish == 1) {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/inactive/id/' .$id);
						$publish = $this->cmsIconButton('Stop Publish this Gallery',$this->imgUrl .'/icon/active.png',$linkPublish);
					} else {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/active/id/' .$id);
						$publish = $this->cmsIconButton('Publish this Gallery',$this->imgUrl .'/icon/inactive.png',$linkPublish);
					}
					$publish_time	= date('d-m-Y H:m:s',strtotime($value['publish_time']));
					//----- lay thong so lock_status
					$lock_status = $value['lock_status'];
					if ($lock_status == 1) {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/inactive/id/' .$id);
						$lock_status = $this->cmsIconButton('Unlock this Gallery',$this->imgUrl .'/icon/lockpage.png',$linkLockStatus);
					} else {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/active/id/' .$id);
						$lock_status = $this->cmsIconButton('Lock this Gallery',$this->imgUrl .'/icon/unlockpage-black.png',$linkLockStatus);
					}
					
					$order = $this->formText('order[' .$value['id'] .']',$value['order'],
											array('style'=> 'width: 30px; text-align: center;'));
								
					$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
					$btnInfo = $this->cmsIconButton('View information',$this->imgUrl .'/icon_info.png',$linkInfo);
					$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
					$btnEdit = $this->cmsIconButton('Edit Item',$this->imgUrl .'/icon_edit.png',$linkEdit);
					$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
					$btnDelete = $this->cmsIconButton('Delete Item',$this->imgUrl .'/icon_del.png',$linkDelete);
					$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
					
					$cid = $this->formCheckbox('cid[]',$value['id']);
			?>
			
			<tr class="even">						
					<td align="center"><?php echo $cid; ?></td>
					<td align="left"><?php echo $gallery_name; ?></td>
					<td align="center"><?php echo $cover_image; ?></td>
					<td align="center"><?php echo $publish; ?></td>
					<td align="center"><?php echo $publish_time; ?></td>
					<td align="center"><?php echo $order; ?></td>
					<td align="center">
						<?php echo $strControlIconButton; ?>
					</td>
					<td align="center"><?php echo $id; ?></td>
					<td align="center"><?php echo $lock_status; ?></td>
			</tr>
			
			<?php 
				} // ------------- dong vong lap foreach ----------------
			?>
	<!--------------------------------------- BEGIN: PAGINATION (FOOT) --------------------------------------->
			<tfoot>
				<tr>
					<td colspan="9">
						<div class="container">
							<div class="pagination">
								<div class="limit">Display #
									<select onchange="submitform();" size="1" class="inputbox" id="limit" name="limit">
										<option value="5">5</option>
									</select>
								</div>
								<div class="limit">
									<?php $currentUrl = $this->baseUrl($this->currentController . '/index'); ?>
									<?php echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); ?>
								</div>
								<div class="limit"></div>
							</div>
						</div>
					</td>
				</tr>					
			</tfoot>				
	<!--------------------------------------- END: PAGINATION (FOOT) --------------------------------------->
		</table>
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>