<?php
	//----- doc du lieu video link tu file config/videolist.ini
	$video = $this->video('production','youtube_embed_video1');
	
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['video_link'] = $video['link'];
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['video_link'] = '';
	}

	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	//----- lay danh sach cac file anh co trong thu muc templates/banner-slide
	$dir = new DirectoryIterator(FILES_PATH . '/templates/logo/');
	$arrLogoImages = array();
	foreach ($dir as $fileInfo) {
		if (!$fileInfo->isDot()) {
			$arrLogoImages[] = $fileInfo->getFilename();
		}
	}
	
	$current_video = '<iframe width="475" height="241" src="' .
					$video['link'] .'" frameborder="0" allowfullscreen></iframe>';
	
	$video_link = $this->formText('video_link',$formdata['video_link'],array('class'=>'txtlong','style'=>$formstyle['video_link']));
	
	$arrInput = array(
			array('label'=>$this->translate('admin-template-video'),'input'=>$current_video),
			array('label'=>$this->translate('admin-template-video-link-new'),'input'=>$video_link),
	);
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-template/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-template/sublink/index.php'); ?>
	
	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX ----------------------------------->

		<div id="filters">
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
			</div>
			<div class="clr"></div>
		</div>
		
		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>