<?php
$product_row =$this->Item;
//$cart=$this->cart;
$dem=0;
$pre_total=0;
/*

*/
?>
<?php
//----- INPUT ELEMENT ---------------------------------------
//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
$formdata = $this->FormData;
$formstyle = $this->FormStyle;
if ($formdata == null) {
	//echo 'here';
	$formdata['quantity'] = $this->quantity;
	$formdata['name'] = '';
	$formdata['email'] = '';
	$formdata['address'] = '';
	$formdata['mobile'] = '';
	$formdata['limit_time'] = '';
	$formdata = $this->cmsReplaceString($formdata);
}
//$formdata['quantity']=$this->quantity;
if (empty($formdata['information'])||!isset($formdata['information'])) {
	$formdata['information'] = '';
}

	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['name'] = '';
		$formstyle['mobile'] = '';
		$formstyle['email'] = '';
		$formstyle['address'] = '';
		$formstyle['mobile'] = '';
		$formstyle['information'] = '';
	}
	
	$name		= $this->formText('name',$formdata['name'],array('class'=>'txtmedium','style'=>$formstyle['name']));
	$address		= $this->formText('address',$formdata['address'],array('class'=>'txtmedium','style'=>$formstyle['address']));
	$mobile		= $this->formText('mobile',$formdata['mobile'],array('class'=>'txtmedium','style'=>$formstyle['mobile']));
	$email		= $this->formText('email',$formdata['email'],array('class'=>'txtmedium','style'=>$formstyle['email']));
	$information		= $this->formText('information',$formdata['information'],array('class'=>'txtmedium','style'=>$formstyle['information']));
	//$order	 		= $this->formText('order',$formdata['order'],array('class'=>//'txtshort','style'=>$formstyle['order']));
	
	
	
	$arrInput = array(
					array('label'=>'Họ và tên','input'=>$name),
					array('label'=>'Địa chỉ','input'=>$address),
					array('label'=>'Mobile','input'=>$mobile),
					array('label'=>'email','input'=>$email),
					array('label'=>'Thông tin thêm','input'=>$information),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}


?>
<?php

$dem++;
$product_id=$product_row['id'];
$name=$product_row['product_name'];
$cover_image = FILES_URL . '/products/cover-images/small/' . $product_row['cover_image'];

							$quantity=$formdata['quantity'];
							$price=$product_row['price'];
							$unit=$product_row['unit'];
							$money=$quantity*$price;
							$pre_total=$money;
							$VAT=10;
							$vat_cost=$pre_total*$VAT*0.01;
							$transport_fee=25000;
							$total=$pre_total+$transport_fee+$vat_cost;
?>
<div class="row">
<div class="col-lg-3 col-md-3 col-sm-12">

				<!-- Best Seller -->
				<div class="col-lg-12 col-md-12 col-sm-6">
	        		<div class="no-padding">
	            		<span class="title"><br></span>
	            	</div>
					<div class="list-group list-categ">
						<a href="catalogue.html" class="list-group-item">Chim sắc màu</a>
						<a href="catalogue.html" class="list-group-item">Chim nghe tiếng hót</a>
						<a href="catalogue.html" class="list-group-item">Chim trĩ(đỏ,xanh,trắng)</a>
						
					</div>
					
				</div>
				<!-- End Best Seller -->
<div id="fb-root"></div>
					<script>(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) return;
					  js = d.createElement(s); js.id = id;
					  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.0";
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));
					</script>
					<div class="fb-like-box" data-href="https://www.facebook.com/FacebookDevelopers" data-width="235" data-height="350" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true">
						
					</div>
</div>			

        	
			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">Đơn đặt hàng</span>
            	</div>
	            <form name="appForm" method="post"
			action="/rausach/cart/checkoutproduct/id/<?php echo $product_id;?>"
			enctype="multipart/form-data">
			<div class="clr"></div>
			<!-- show cart-->
			<div class="col-lg-12 col-sm-12 hero-feature">
				<table class="table table-bordered tbl-cart">
					<thead>
						<tr>
							<td>TT</td>
							<td class="hidden-xs">Ảnh</td>
							<td>Tên sản phẩm</td>
							<td>ĐVT</td>
							<td class="td-qty">Số lượng</td>
							<td>Đơn giá</td>
							<td>Thành tiền</td>
							<td>Tác vụ</td>
						</tr>
					</thead>
					<tbody>


						<tr>
							<td><?php echo $dem;?></td>
							<td class="hidden-xs"><a href="detail.html"> <img
									src="<?php echo $cover_image; ?>"
									alt="Age Of Wisdom Tan Graphic Tee" title="" width="47"
									height="47">
							</a>
							</td>
							<td width="20%"><a href="detail.html"><?php echo $name;?> </a>
							</td>

							<td width="10%"><?php echo $unit;?></td>
							<td width="20%">
								<div class="input-group bootstrap-touchspin" style="">
									<input type="text" class="input-qty form-control text-center"
										id="quantity" name="quantity" value="<?php echo $quantity;?>"
										onkeyup="change_quantity()" />
							
							</td>
							<td class="price" id="price"><?php echo $price;?></td>
							<td><div id="money">
									<?php echo $money;?>
								</div></td>
							<td><span class="glyphicon glyphicon-trash"></span></td>
						</tr>

						<tr>
							<td colspan="6" align="right">Giá bán trước thuế:</td>
							<td class="total" colspan="2"><b id="pre_total"><?php echo $pre_total;?>
							</b>
						
						</tr>
						<tr>
							<td colspan="6" align="right">Phí vận chuyển:</td>
							<td class="total" colspan="2"><b><?php echo $transport_fee;?> </b>
							</td>
						</tr>
						<tr>
							<td colspan="6" align="right">VAT <?php echo $VAT;?>%:
							</td>
							<td class="total" colspan="2"><b id="VAT"><?php echo $vat_cost;?>
							</b>
							</td>
						</tr>
						<tr>
							<td colspan="6" align="right">Tổng cộng:</td>
							<td class="total" colspan="2"><b id="total"><?php echo $total;?>
							</b>
							</td>
						</tr>
					</tbody>
				</table>


				<div class="form-group">
					<?php
			if(!empty($errors)) {
	?>
					<div class="alert alert-danger">
						<?php echo $errors; ?>
					</div>
					<?php 
		}
		?>
				</div>
			</div>
			<!-- end show cart-->
<div class="col-lg-12 col-sm-12" style="margin-bottom: 10px; text-align: center;">
				
            		<span class="center-body">
					<a href="#" >Xem lại sản phẩm vừa đặt hàng</a>
					<a href="#" >Quay về danh sách sản phẩm </a> 
					</span>
            	</div>
				<div class="col-lg-12 col-sm-12 hero-feature">
					<div class="">
					- Quý khách có thể điều chỉnh số lượng cần mua tại cột “Số lượng”. <br>
	- Quý khách mua hàng có số tiền thanh toán lớn hơn 800.000 VNĐ được miễn phí vận chuyển trong nội thành phạm vi bán kính 5 Km. <br>
	- Nếu địa điểm nhận hàng có khoảng cách xa trên 5 km (tính từ Trụ sở Công ty – Phố Quốc Tử Giám, Hà Nội) hoặc số tiền thanh toán nhỏ hơn 800.000 VND, Quý khách vui lòng thanh toán thêm phí vận chuyển 35.000 VND/ Tổng đơn hàng. <br>
	- Đối với sản phẩm Con giống và một số hàng hóa Thực phẩm sạch đặc biệt sẽ tính chi phí vận chuyển theo phát sinh thực tế.<br>
					</div>
					
					<span class="title" style="padding: 10px 0 10px 0;color: #08382A;
font-size: 14px;">Thông tin Khách đặt hàng:</span>
Để gửi đơn đặt hàng, Quý khách vui lòng điền các thông tin dưới đây:
<br>
					
				</div>

			<!--------------------------------------- BEGIN: CONTENT ---------------------------------->
			<div id="element-box">
				<div class="t">
					<div class="t">
						<div class="t"></div>
					</div>
				</div>
				<div class="m">

	<!--------------------------------------- form add group ---------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				 <div id="row" class="row">
                    <div class="col-lg-2">
                        <strong>Time</strong>
                    </div>
                    <div class="col-lg-10">
                        <input type="text" name="limit_time" value="" id="date"/>
                        <script>
                            $('#date').datepicker();
                        </script>
                    </div>
                </div>
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<input type="submit" name="ok" action="">
	<!--------------------------------------- END: CONTENT ---------------------------------->
<input type="hidden" id="hdtotal" name="total" value="<?php echo $total;?>"/> 

		</form>
		<input type="hidden" id="hdprice" value="<?php echo $price;?>" />

		<script> function change_quantity(){
var vat= <?php echo $VAT ?>;
var transport_fee=<?php echo $transport_fee ?>;
var price=$("#hdprice").val();//alert(price);
var quantity=$("#quantity").val();//alert(quantity);
var total_change=price*quantity;//alert(total_change);
var vat_cost=total_change*vat*0.01;//alert(vat_cost);
var total=total_change+vat_cost+transport_fee;//alert(total);
$("#pre_total").html(total_change);
$("#money").html(total_change);
$("#VAT").html(vat_cost);
$("#total").html(total);
$("#hdtotal").val(total);

}


</script>

				
        	</div>
        	<!-- End Cart -->


        </div>