<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;

	if ($formdata == null) {
		$formdata['project_category_id'] = 0;
		$formdata['project_title'] = '';
		$formdata['project_brief'] = '';
		$formdata['project_content'] = '';
		$formdata['cover_image'] = '';
		$formdata['publish'] = 0;
		$formdata['order'] = 0;
		$formdata['created_id'] = 0;
		$formdata['created_name'] = '';
		$formdata['created_time'] = '0000-00-00 00:00:00';
		$formdata['last_modified_id'] = 0;
		$formdata['last_modified_name'] = '';
		$formdata['last_modified_time'] = '0000-00-00 00:00:00';
		$formdata['publisher_id'] = 0;
		$formdata['publish_time'] = '0000-00-00 00:00:00';
		$formdata['hit_counter'] = 0;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$linkProjectCat	= $this->baseUrl('/admin/admin-project-category/info/id/' .$formdata['project_category_id']);
	$category_name		= '<a href="' . $linkProjectCat . '">' . $formdata['category_name'] . '</a>';
	
	$project_title 	= $formdata['project_title'];
	$project_brief 	= $formdata['project_brief'];
	$project_content = $formdata['project_content'];
	$publish		= $formdata['publish'];
	if ($publish == 0) {
		$publish = $this->translate('admin-cw-publish');
	} else {
		$publish = $this->translate('admin-cw-nopublish');
	}
	$order 	= $formdata['order'];
	
	//----- CREATE: cover image option --------------------------
	$cover_image 	= FILES_URL . '/projects/cover-images/small/' . $formdata['cover_image'];
	$cover_image	= '<img src="' . $cover_image .'"/><br/>';
	
	$created_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['created_id']) . '">' . $formdata['created_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$created_time	= date('d/m/Y H:i:s',strtotime($formdata['created_time']));
	
	$last_modified_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['last_modified_id']) . '">' . $formdata['last_modified_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$last_modified_time	= date('d/m/Y H:i:s',strtotime($formdata['last_modified_time']));
	
	$arrInput = array(
					array('label'=>$this->translate('admin-project-add-label-projectcategory'),'input'=>$category_name),
					array('label'=>$this->translate('admin-project-add-label-projecttitle'),'input'=>$project_title),
					array('label'=>$this->translate('admin-project-add-label-projectbrief'),'input'=>$project_brief),
					array('label'=>$this->translate('admin-project-add-label-projectcontent'),'input'=>$project_content),
					array('label'=>$this->translate('admin-project-add-label-projectcoverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-cp-createdby'),'input'=>$created_name),
					array('label'=>$this->translate('admin-cp-createdtime'),'input'=>$created_time),
					array('label'=>$this->translate('admin-cp-lastmodifiedby'),'input'=>$last_modified_name),
					array('label'=>$this->translate('admin-cp-lastmodifiedtime'),'input'=>$last_modified_time),
			);
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-project/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-project/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>