<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblCategoryName = $this->cmsSortLink('pc.category_name',$this->arrParam,$this->translate('admin-projectcategory-col-categoryname'),$this->imgUrl,$action_link);
	$lblCategoryID = $this->cmsSortLink('pc.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblCategoryDesc = $this->cmsSortLink('pc.description',$this->arrParam,$this->translate('admin-cw-description'),$this->imgUrl,$action_link);
	$lblCategoryPublish = $this->cmsSortLink('pc.publish',$this->arrParam,$this->translate('admin-cw-publish'),$this->imgUrl,$action_link);
	$lblCategoryPublishTime = $this->cmsSortLink('pc.publish_time',$this->arrParam,$this->translate('admin-cp-publishtime'),$this->imgUrl,$action_link);
	$lblCategoryOrder = $this->cmsSortLink('pc.order',$this->arrParam,$this->translate('admin-cw-order'),$this->imgUrl,$action_link);
	$lblCategoryLockStatus = $this->cmsSortLink('pc.lock_status',$this->arrParam,$this->translate('admin-cw-lock'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->OrderErrorMessage) > 0) {
		$errors = $this->formErrors($this->OrderErrorMessage,array('id'=>'errors'));
	}
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-project-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-project-category/sublink/index.php'); ?>
	
	<!-- ------------------------------------ table Admin verion 2 ------------------------- -->
	<div class="panel panel-default adminlist">
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover" id="dataTables-object">
					<thead>
						<tr>
							<th width="43" >
								<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
							</th>
							<th><?php echo $this->translate('admin-projectcategory-col-categoryname'); ?></th>
							<th class="col_newscat_desc"><?php echo $this->translate('admin-cw-description'); ?></th>
							<th class="col_order"><?php echo $this->translate('admin-cw-order'); ?></th>
							<th class="col_publish"><?php echo $this->translate('admin-cw-publish'); ?></th>
							<th class="col_publish_time"><?php echo $this->translate('admin-cp-publishtime'); ?></th>
							<th class="col_control">Control</th>
							<th class="col_lock_status"><?php echo $this->translate('admin-cw-lock'); ?></th>
					</tr>
					</thead>
					<tbody>
                                    
					<?php
						$OrderErrorStyle 	= $this->OrderErrorStyle;
						$OrderErrorData 	= $this->OrderErrorData;
						
						//----- sap xep lai danh sach cac category theo quan he cha-con, dua vao mang $newArray
						$sourceArr = $this->Items;
						$objRecursive = new Zendvn_System_Recursive();
						$newArray = array();
						$objRecursive->recursive($sourceArr, 0, 1, $newArray);
						
						foreach ($newArray as $key => $value) {
							$value = $this->cmsReplaceString($value);
							$id = $value['id'];
							$category_name = $value['category_name'];
							
							if ($value['level'] == 1) {
								$category_name = $value['category_name'];
							} else {
								$string = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
								$string = '- - - - - ';
								$newString = '';
								for ($i=1; $i< $value['level']; $i++) {
									$newString .= $string;
								}
								$category_name = $newString .$value['category_name'];
							}
							
							$description = $value['description'];
							$status = $value['status'];
							$order = $value['order'];
							$orderStyle = 'width: 30px; text-align: center;';
							if (!empty($OrderErrorStyle[$value['id']])) {
								$orderStyle .= $OrderErrorStyle[$value['id']];
							}
							$orderValue = $value['order'];
							if ($OrderErrorData[$value['id']] > 0) {
								$orderValue = $OrderErrorData[$value['id']];
							}
							
							$lock_status = $value['lock_status'];
							if ($lock_status == 1) {
								$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/inactive/id/' .$id);
								$lock_status = $this->cmsIconButton('This category is locked','fa fa-lock',$linkLockStatus,'css');
							} else {
								$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/active/id/' .$id);
								$lock_status = $this->cmsIconButton('This category is unlocked','fa fa-unlock',$linkLockStatus,'css');
							}
							
							//----- neu doi tuong bi khoa thi vo hieu hoa o textbox order
							if ($value['lock_status'] == 0) {
								$order = $this->formText('order[' .$value['id'] .']',$value['order'],
										array('style'=> 'width: 30px; text-align: center;'));
							} else if ($value['lock_status'] == 1) {
								$order = $this->formText('order[' .$value['id'] .']',$value['order'],
										array('style'=> 'width: 30px; text-align: center;','disabled'=>true));
							}
							
							$publish = $value['publish'];
							if ($publish == 1) {
								$linkPublish = $this->baseUrl($this->currentController .'/publish/type/inactive/id/' .$id);
								$publish = $this->cmsIconButton('Stop Publish this article','fa fa-check',$linkPublish,'css');
							} else {
								$linkPublish = $this->baseUrl($this->currentController .'/publish/type/active/id/' .$id);
								$publish = $this->cmsIconButton('Publish this article','fa fa-minus-circle',$linkPublish,'css');
							}
							//----- chuyen publish_time tu dang Y-m-d sang d-m-Y de hien thi ra view
							$publish_time = date('d/m/Y H:i:s',strtotime($value['publish_time']));
							
							$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
							$btnInfo = $this->cmsIconButton('View information','fa fa-info-circle fa-lg',$linkInfo,'css');
							$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
							$btnEdit = $this->cmsIconButton('Edit Item','fa fa-edit fa-lg',$linkEdit,'css');
							$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
							$btnDelete = $this->cmsIconButton('Delete Item','fa fa-times-circle fa-lg',$linkDelete,'css');
							$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
							
							$cid = $this->formCheckbox('cid[]',$value['id']);
					?>
			
					<tr class="odd gradeX even">						
						<td align="center"><?php echo $cid; ?></td>
						<td align="left"><?php echo $category_name; ?></td>
						<td align="center"><?php echo $description; ?></td>
						<td align="center"><?php echo $order; ?></td>
						<td align="center"><?php echo $publish; ?></td>
						<td align="center"><?php echo $publish_time; ?></td>
						<td align="center">
							<?php echo $strControlIconButton; ?>
						</td>
						<td align="center"><?php echo $lock_status; ?></td>
					</tr>
			
                <?php 
				} // ------------- dong vong lap foreach ----------------
			?>                    
                                        
					</tbody>
				</table>
			</div> <!-- /.table-responsive -->
		</div> <!-- /.panel-body -->
	</div>
	<!-- -------------------------------- End table Admin verion 2 ------------------------- -->
	
	
</form>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-object').dataTable();
    });
</script>