<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;
	$projectCount = $this->projectCount;

	if ($projectCount == 0) {
		$strProjectCount = $this->translate('admin-projectcategory-info-nonews');
	} else {
		$strProjectCount = '<span style="font-size: 15pt;">' .$projectCount .'</span>' . $this->translate('admin-projectcategory-info-havenews');
	}

	if ($formdata == null) {
		$formdata['category_name'] = '';
		$formdata['description'] = 0;
		$formdata['status'] = 1;
		$formdata['order'] = 1;
		$formdata['created_by'] = 0;
		$formdata['created'] = '';
		$formdata['user_id'] = 0;
		$formdata['user_name'] = '';
		$formdata['created_id'] = 0;
		$formdata['created_name'] = '';
		$formdata['created_time'] = '0000-00-00 00:00:00';
		$formdata['last_modified_id'] = 0;
		$formdata['last_modified_name'] = '';
		$formdata['last_modified_time'] = '0000-00-00 00:00:00';
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$category_name 	= $formdata['category_name'];
	$description 	= $formdata['description'];
	$order			= $formdata['order'];
	$status			= $formdata['status'];
	if ($status == 0) {
		$status 	= $this->translate('admin-userinfo-inactive');
	} else {
		$status 	= $this->translate('admin-userinfo-active');
	}
	
	$created_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['created_id']) . '">' . $formdata['created_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$created_time	= date('d/m/Y H:i:s',strtotime($formdata['created_time']));
	
	$last_modified_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['last_modified_id']) . '">' . $formdata['last_modified_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$last_modified_time	= date('d/m/Y H:i:s',strtotime($formdata['last_modified_time']));
	
	$arrInput = array(
					array('label'=>$this->translate('admin-projectcategory-col-categoryname'),'input'=>$category_name,'style'=>'font-size: 15pt;'),
					array('label'=>$this->translate('admin-cw-description'),'input'=>$description),
					array('label'=>$this->translate('admin-cw-status'),'input'=>$status),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-projectcategory-info-totalnews'),'input'=>$strProjectCount),
					array('label'=>$this->translate('admin-cp-createdby'),'input'=>$created_name),
					array('label'=>$this->translate('admin-cp-createdtime'),'input'=>$created_time),
					array('label'=>$this->translate('admin-cp-lastmodifiedby'),'input'=>$last_modified_name),
					array('label'=>$this->translate('admin-cp-lastmodifiedtime'),'input'=>$last_modified_time),
			);	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-project-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-project-category/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>