	<?php
		if (!empty($this->Item)) {
      //var_dump($this->Item);
			$thisProduct = $this->cmsReplaceString($this->Item);
			$product_id = $thisProduct['id'];
			$product_name = $thisProduct['product_name'];
			$price = $thisProduct['price'];
      $manufacturer = $thisProduct['manufacturer'];
      $product_assessment = $thisProduct['product_assessment'];
      $product_guarantee = $thisProduct['product_guarantee'];
      $product_model = $thisProduct['product_model'];
      $product_code = $thisProduct['product_code'];
      $product_guarantee_policy = $thisProduct['product_guarantee_policy'];
      $product_price_new = $thisProduct['product_price_new'];
			$cover_image = FILES_URL . '/products/cover-images/medium/' . $thisProduct['cover_image'];
			$product_detail = $thisProduct['product_detail'];
      $category_name = $thisProduct['category_name'];
      
		}
		
	?>
      <div class="row">
        <ol class="breadcrumb">
          <li>
            <a href="/index">Trang chủ</a>
          </li>
          <li>
            <a href="/default/san-pham">Sản phẩm</a>
          </li>
          <li>
            <a href="#"><?php echo $category_name ?></a>
          </li>
          <li class="active"><?php echo $product_name; ?></li>
        </ol>
      </div>

      <div class="row">
        <div id="details" class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
              <div class="details-img">
                <img src="<?php echo $cover_image; ?>" class="img-responsive" alt="Image">
              </div>
              <div class="details-thumb first">
                <img src="<?php echo $cover_image; ?>" class="img-responsive" alt="Image">
              </div>
              <div class="details-thumb center">
                <img src="<?php echo $cover_image; ?>" class="img-responsive" alt="Image">
              </div>
              <div class="details-thumb">
                <img src="<?php echo $cover_image; ?>" class="img-responsive" alt="Image">
              </div>
            </div>
            <span class="fb_google"></span>
          </div>
          <img src="" id="details_img_temp" style="display:none">
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 details-info">
            <h4><?php echo $product_name; ?></h4>
            <span class="code">Model: <?php echo $product_model; ?> &nbsp; | &nbsp; Mã hàng: <?php echo $product_code; ?></span>
            <hr />
            <ul>
             
              <li>Bảo hành: <?php echo $product_guarantee ?></li>
              <li>Hàng sản xuất: <?php echo $manufacturer ?></li>
            </ul>

            <span class="price-big"><?php echo $product_price_new; ?></span> 
			      <span>(Giá chính hãng: <?php echo $price; ?>)</span>
            
          </div>

          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <ul class="nav navbar-nav tab pull-left">
              <li class="first active">
                <a id="tab1" class="tab-link" href="#">Chi tiết sản phẩm</a>
              </li>
              <li>
                <a id="tab2" class="tab-link" href="#">Đánh giá</a>
              </li>
              <li>
                <a id="tab3" class="tab-link" href="#">Chính sách bảo hành</a>
              </li>
            </ul>
          </div>

          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 content">
            <div id="tab1-content" class="tab-cnt">

<?php echo $product_detail; ?>


            </div>


            <div id="tab2-content" class="tab-cnt" style="display:none">
              <?php echo $product_assessment; ?>
            </div>
            <div id="tab3-content" class="tab-cnt" style="display:none">
              <?php echo $product_guarantee_policy; ?>
            </div>
          </div>
        </div>
        <div id="right" class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-center">
          <div class="list-product2">
            
         <?php echo $this->blkRelativeProduct(); ?>        

          </div>
          <div id="support">
            <span class="support-title">Bạn cần trợ giúp</span> <br />
            <span>Hãy liên hệ <span>0988x8x8x</span></span> <br />
            <span>(Mrs Phương)</span>
          </div>
        </div>
      </div>

    