<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$curControllerLink = $this->baseUrl($this->currentController);
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/index/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/index/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>