<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-productcategoryattribute-delete-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}

	$attribute_name 	= $this->cmsReplaceString($this->Item['attribute_name']);
	$product_category_name = $this->cmsReplaceString($this->Item['product_category_name']);
	//----- thong bao loi -----
	$errors = '';
	$messageError = $this->messageError;
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-product-category-attribute/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-product-category-attribute/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<div id = "errors">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-productcategoryattribute-add-label-attributename'); ?></div>
					<div style="font-size: 15pt;"><?php echo $attribute_name; ?>
						<?php if (!empty($messageError)) { ?>
							<div id = "errors" style="margin-top: 8px;">
								<?php echo $messageError; ?>
							</div>
						<?php } ?>
					</div>
				</div>
				
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-productcategory-add-label-categoryname') ?></div>
					<div><?php echo $product_category_name; ?></div>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>