<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblCategoryName = $this->cmsSortLink('pc.category_name',$this->arrParam,$this->translate('admin-productcategory-col-categoryname'),$this->imgUrl,$action_link);
	$lblAttributeName = $this->cmsSortLink('pca.attribute_name',$this->arrParam,$this->translate('admin-productcategoryattribute-col-attributename'),$this->imgUrl,$action_link);
	$lblAttributeID = $this->cmsSortLink('pca.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblAttributePublish = $this->cmsSortLink('pca.publish',$this->arrParam,$this->translate('admin-cw-publish'),$this->imgUrl,$action_link);
	$lblAttributePublishTime = $this->cmsSortLink('pca.publish_time',$this->arrParam,$this->translate('admin-cp-publishtime'),$this->imgUrl,$action_link);
	$lblAttributeOrder = $this->cmsSortLink('pca.order',$this->arrParam,$this->translate('admin-cw-order'),$this->imgUrl,$action_link);
	$lblAttributeLockStatus = $this->cmsSortLink('pca.lock_status',$this->arrParam,$this->translate('admin-cp-lockstatus'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
	//--------------------------------------- CREATE: PRODUCT CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbProductCat;
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/productcategory');
	$slbProductCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),
			array('name'=>'category_id','onChange'=>"OnSubmitForm('" .$linkSearch ."')","value"=>$ssFilter['category_id']));
	$selectCategory = 'Product Category: ' .$slbProductCat;
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	$formOrderData = array();
	$formOrderStyle = array();
	if (isset($formdata['order'])) {
		$formOrderData = $formdata['order'];
	}
	if (isset($formstyle['order'])) {
		$formOrderStyle = $formstyle['order'];
	}
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-product-category-attribute/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-product-category-attribute/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX - SEARCH AREA----------------------------------->
			<?php echo $errors; ?>
			
			<div id="filters">
				<div style="float: left">
					<?php echo $strSearch; ?>
				</div>
				<div style="float: right">
					<?php echo $selectCategory; ?>
				</div>
				<div class="clear"></div>
				
			</div>

		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		<table class="adminlist">
			<thead>
				<tr>
					<th class="col_cid">
						<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
					</th>
					<th><?php echo $lblCategoryName; ?></th>
					<th><?php echo $lblAttributeName; ?></th>
					<th class="col_order"><?php echo $lblAttributeOrder; ?></th>
					<th class="col_publish"><?php echo $lblAttributePublish; ?></th>
					<th class="col_publish_time"><?php echo $lblAttributePublishTime; ?></th>
					<th class="col_control">Control</th>
					<th class="col_id"><?php echo $lblAttributeID; ?></th>
					<th class="col_lock_status"><?php echo $lblAttributeLockStatus; ?></th>
				</tr>
			</thead>
			
			<?php
				foreach ($this->Items as $key => $value) {
					$value = $this->cmsReplaceString($value);
					$id = $value['id'];
					
					$category_name = $value['category_name'];
					$attribute_name = $value['attribute_name'];
					
					$publish = $value['publish'];
					if ($publish == 1) {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/inactive/id/' .$id);
						$publish = $this->cmsIconButton('Stop Publish this attribute',$this->imgUrl .'/icon/active.png',$linkPublish);
					} else {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/active/id/' .$id);
						$publish = $this->cmsIconButton('Publish this attribute',$this->imgUrl .'/icon/inactive.png',$linkPublish);
					}
					$publish_time	= date('d/m/Y H:i:s',strtotime($value['publish_time']));
					
					$lock_status = $value['lock_status'];
					if ($lock_status == 1) {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/inactive/id/' .$id);
						$lock_status = $this->cmsIconButton('This attribute is locked',$this->imgUrl .'/icon/lockpage.png',$linkLockStatus);
					} else {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/active/id/' .$id);
						$lock_status = $this->cmsIconButton('This attribute is unlocked',$this->imgUrl .'/icon/unlockpage-black.png',$linkLockStatus);
					}
					
					$orderStyle = 'width: 30px; text-align: center;';
					if (!empty($formOrderStyle[$value['id']])) {
						$orderStyle .= $formOrderStyle[$value['id']];
					}
					$orderValue = $value['order'];
					if (isset($formOrderData[$value['id']])) {
						$orderValue = $formOrderData[$value['id']];
					}
					//----- neu doi tuong bi khoa thi vo hieu hoa o textbox order
					if ($value['lock_status'] == 0) {
						$order = $this->formText('order[' .$value['id'] .']',$orderValue,
								array('style'=> $orderStyle));
					} else if ($value['lock_status'] == 1) {
						$order = $this->formText('order[' .$value['id'] .']',$orderValue,
								array('style'=> $orderStyle,'disabled'=>true));
					}
					
					$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
					$btnInfo = $this->cmsIconButton('View information',$this->imgUrl .'/icon/icon_info.png',$linkInfo);
					$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
					$btnEdit = $this->cmsIconButton('Edit Item',$this->imgUrl .'/icon/icon_edit.png',$linkEdit);
					$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
					$btnDelete = $this->cmsIconButton('Delete Item',$this->imgUrl .'/icon/icon_del.png',$linkDelete);
					$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
					
					$cid = $this->formCheckbox('cid[]',$value['id']);
			?>
			
			<tr class="even">						
					<td align="center"><?php echo $cid; ?></td>
					<td align="left"><?php echo $category_name; ?></td>
					<td align="left"><?php echo $attribute_name; ?></td>
					<td align="center"><?php echo $order; ?></td>
					<td align="center"><?php echo $publish; ?></td>
					<td align="center"><?php echo $publish_time; ?></td>
					<td align="center"><?php echo $strControlIconButton; ?></td>
					<td align="center"><?php echo $id; ?></td>
					<td align="center"><?php echo $lock_status; ?></td>
			</tr>
			
			<?php 
				} // ------------- dong vong lap foreach ----------------
			?>
	<!--------------------------------------- BEGIN: PAGINATION (FOOT) --------------------------------------->
			<tfoot>
				<tr>
					<td colspan="9">
						<div class="container">
							<div class="pagination">
								<div class="limit">Display #
									<select onchange="submitform();" size="1" class="inputbox" id="limit" name="limit">
										<option value="5">5</option>
									</select>
								</div>
								<div class="limit">
									<?php $currentUrl = $this->baseUrl($this->currentController . '/index'); ?>
									<?php echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); ?>
								</div>
								<div class="limit"></div>
							</div>
						</div>
					</td>
				</tr>					
			</tfoot>				
	<!--------------------------------------- END: PAGINATION (FOOT) --------------------------------------->
		</table>
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>