<div class="col-md-8">
	<h3>Dịch vụ của chúng tôi</h3>
	<hr/>
	<?php 
	$serviceList = $this->serviceList;
	if (!empty($serviceList) && count($serviceList) > 0) {
		foreach ($serviceList as $key=>$val) {
			$val = $this->cmsReplaceString($val);
			$service_id 		= $val['id'];
			$service_title		= $val['service_title'];
			$service_brief 		= $val['service_brief'];
			$cover_image 		= FILES_URL . '/services/cover-images/medium/' . $val['cover_image'];
				
			$filter = new Zend_Filter();
			$multiFilter = $filter->addFilter(new Zend_Filter_StringToLower(array('encoding'=>'UTF-8')))
								 ->addFilter(new Zend_Filter_StringTrim())
								 ->addFilter(new Zend_Filter_Alnum(true))
								 ->addFilter(new Zendvn_Filter_RemoveCircumflex())
								 ->addFilter(new Zend_Filter_Word_SeparatorToDash(' '));
				
			$serviceUrlOptions = array('module'=>'default','controller'=>'dich-vu','action'=>'dich-vu-chi-tiet',
					'title'=>$multiFilter->filter($service_title),'id'=>$service_id);
				
			$service_link = $this->url($serviceUrlOptions,'service');
	?>
	
	<div class="row">
		<div class="col-md-12">
			<img src="<?php echo $cover_image; ?>" alt="cnt dich vu 1" class="img-thumbnail service-thumb"/>
			<div class="service-introduce">
				<h4 class="service-heading"><a href="<?php echo $service_link; ?>"><?php echo $service_title; ?></a></h4>
				<p><?php echo $service_brief; ?></p>
				<a href="<?php echo $service_link; ?>"><button type="button" class="btn btn-primary cnt-detail-button">Chi tiết</button></a>
			</div>
		</div>
	</div>
	
	<?php 
		}
	} else {
	?>
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-danger">Không có dịch vụ nào thuộc mục này!</div>
		</div>
	</div>
	<?php 
	}
	?>
	
	<!-- ********************************** phan trang **************************************-->
	<?php 
		$paginator = $this->paginator;
		if(!empty($paginator) && ($paginator->count()) > 1) {
	?>
	<ul class="pagination pagination">
		<?php $currentUrl = $this->baseUrl($this->currentController . '/index'); ?>
		<?php echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); ?>
	</ul>
	<?php } ?>
	<!-- ********************************** End phan trang **********************************-->
	
</div>