<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-contact-delete-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}
	$contact = $this->cmsReplaceString($this->Item);
	$contact_name 	= $contact['contact_name'];
	$contact_email = $contact['email'];
	$contact_mobile = $contact['mobile'];
	$contact_content = $contact['contact_content'];
	$post_time	= date('d-m-Y H:m:s',strtotime($contact['post_time']));
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-contact/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-contact/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<div id = "errors">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-contact-index-col-contactname'); ?></div>
					<div style="font-size: 15pt;"><?php echo $contact_name; ?></div>
				</div>
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-cw-email'); ?></div>
					<div><?php echo $contact_email; ?></div>
				</div>
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-cw-mobile'); ?></div>
					<div><?php echo $contact_mobile; ?></div>
				</div>
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-cw-content'); ?></div>
					<div><?php echo $contact_content; ?></div>
				</div>
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-cp-posttime'); ?></div>
					<div><?php echo $post_time; ?></div>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>