<!DOCTYPE html>
<html lang="vi">
  <head>
      <?php echo $this->headTitle(); ?>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headLink(); ?>
   <?php echo $this->headScript(); ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ngọc Phương Shop</title>

    <!-- Bootstrap CSS -->
   

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

    <div class="container">

      <?php include ("includes/header.php"); ?>

      <div id="topmenu" class="row">
        
      <?php echo $this->blkProductCategory(); ?>

      </div>


     <!-- ***************************** Banner slide ************************ -->
  <?php include ("includes/banner-slide.php"); ?>


<!-- content -->
<?php echo $this->layout()->content; ?>


 <?php include("includes/footer.php"); ?>

    </div>
    <br />

  <!-- jQuery -->
  

  </body>
</html>