<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-productcategory-edit-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}

	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['parent_category_id'] = 0;
		$formdata['category_name'] = '';
		$formdata['description'] = '';
		$formdata['lock_status'] = 1;
		$formdata['publish'] = 1;
		$formdata['order'] = 0;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['category_name'] = '';
		$formstyle['order'] = '';
	}

	$category_name	= $this->formText('category_name',$formdata['category_name'],array('class'=>'txtmedium','style'=>$formstyle['category_name']));
	$order	 		= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	$description	= $this->formText('description',$formdata['description'],array('class'=>'txtmedium'));
	
	//--------------------------------------- CREATE: PARENT PRODUCT CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbProCat;
	$slbProductCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),
			array('name'=>'parent_category_id','value'=>$formdata['parent_category_id']));
	$selectCategory = $slbProductCat;
	
//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-product-category_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->Item['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-productcategory-add-publish-warning') . $this->formHidden('publish',0);
	}
	
	//----- CREATE: lock status option --------------------------
	if (in_array('admin_admin-product-category_change-lock-status', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->Item['lock_status'] = 0;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-productcategory-add-lockstatus-warning') . $this->formHidden('lock_status',0);
	}
	
	$arrInput = array(
					array('label'=>$this->translate('admin-productcategory-add-label-parent'),'input'=>$selectCategory),
					array('label'=>$this->translate('admin-productcategory-add-label-categoryname'),'input'=>$category_name),
					array('label'=>$this->translate('admin-cw-description'),'input'=>$description),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-cw-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-cp-lockstatus'),'input'=>$lock_status),		
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-news-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-news-category/sublink/index.php'); ?>

	<?php
		if(!empty($errors)) {
	?>
		<div class="alert alert-danger"><?php echo $errors; ?></div>
	<?php 
		}
	?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>