<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['category_id'] = 0;
		$formdata['title'] = '';
		$formdata['brief'] = '';
		$formdata['content'] = '';
		$formdata['duration'] = '';
		$formdata['price'] = '';
		$formdata['start_time'] = '';
		$formdata['start_location'] = '';
		$formdata['tour_path'] = '';
		$formdata['homepage'] = 0;
		$formdata['cover_image'] = '';
		$formdata['publish'] = 1;
		$formdata['lock_status'] = 1;
		$formdata['order'] = $this->lastTourOrder + 1;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['title'] = '';
		$formstyle['brief'] = '';
		$formstyle['content'] = '';
		$formstyle['duration'] = '';
		$formstyle['price'] = '';
		$formstyle['start_time'] = '';
		$formstyle['start_location'] = '';
		$formstyle['tour_path'] = '';
		$formstyle['category_id'] = 'min-width: 200px';
		$formstyle['cover_image'] = '';
		$formstyle['order'] = '';
	}
	//----- CREATE: TOUR CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbTourCat;
	$slbTourCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),array('name'=>'category_id'));
	
	$tour_title 	= $this->formText('title',$formdata['title'],array('class'=>'txtlong','style'=>$formstyle['title']));
	$tour_brief 	= $this->formText('brief',$formdata['brief'],array('class'=>'txtlong','style'=>$formstyle['brief']));
	$tour_content 	= $this->cmsEditor('content',$formdata['content'],array('toolbar'=>'FullToolbar'),array('style'=>'margin-left: 175px;'));
	
	$tour_duration 	= $this->formText('duration',$formdata['duration'],array('class'=>'txtlong','style'=>$formstyle['duration']));
	$tour_price 	= $this->formText('price',$formdata['price'],array('class'=>'txtlong','style'=>$formstyle['price']));
	$tour_starttime	= $this->formText('start_time',$formdata['start_time'],array('class'=>'txtlong','style'=>$formstyle['start_time']));
	$tour_startlocation = $this->formText('start_location',$formdata['start_location'],array('class'=>'txtlong','style'=>$formstyle['start_location']));
	$tour_path 	= $this->formText('tour_path',$formdata['tour_path'],array('class'=>'txtlong','style'=>$formstyle['tour_path']));
	
	$tour_homepage 	= $this->formCheckbox('homepage',null,array('checked'=>$formdata['homepage']));
	
	$imageSize = $this->imageSize('production','tour_cover_image_large');
	$strRecommendSize = ' (recommend image size: ' .$imageSize['width'] .'px-' .$imageSize['height'] .'px)';
	$cover_image 	= $this->formFile('cover_image',array('style'=>$formstyle['cover_image'])) .$strRecommendSize;
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-tour_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->Item['publish'] = 0;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-tour-add-warning') . $this->formHidden('publish',0);
	}
	
	//----- CREATE: lock option ---------------------
	//----- lay du lieu cap phep cua nguoi dung login de xac dinh nguoi dung nay
	//----- co quyen lock/unlock page hay khong
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-tour_change-lock-status', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->FormData['lock_status'] = 1;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-tour-add-warning') . $this->formHidden('lock_status',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));

	$arrInput = array(
					array('label'=>$this->translate('admin-tour-add-label-tourcategory'),'input'=>$slbTourCat),
					array('label'=>$this->translate('admin-tour-add-label-tourtitle'),'input'=>$tour_title),
					array('label'=>$this->translate('admin-tour-add-label-tourbrief'),'input'=>$tour_brief),
					array('label'=>$this->translate('admin-tour-add-label-tourcontent'),'input'=>$tour_content,'style'=>'margin-left: 175px;'),
					array('label'=>$this->translate('admin-tour-add-label-tourduration'),'input'=>$tour_duration),
					array('label'=>$this->translate('admin-tour-add-label-tourprice'),'input'=>$tour_price),
					array('label'=>$this->translate('admin-tour-add-label-tourstarttime'),'input'=>$tour_starttime),
					array('label'=>$this->translate('admin-tour-add-label-tourstartlocation'),'input'=>$tour_startlocation),
					array('label'=>$this->translate('admin-tour-add-label-tourpath'),'input'=>$tour_path),
					array('label'=>$this->translate('admin-tour-add-label-homepage'),'input'=>$tour_homepage),
					array('label'=>$this->translate('admin-tour-add-label-coverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-tour-add-label-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-tour-add-label-lockstatus'),'input'=>$lock_status),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-tour/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-tour/sublink/index.php'); ?>

	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>