<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-tour-delete-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}
	$tour_title 	= $this->cmsReplaceString($this->Item['title']);
	$cover_image = FILES_URL . '/tour/cover-images/small/' . $this->Item['cover_image'];
	$cover_image = '<img src="' . $cover_image . '"/>';
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-tour/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-tour/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<div id = "errors">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-tour-col-tourtitle'); ?></div>
					<div style="font-size: 15pt;"><?php echo $tour_title; ?></div>
				</div>
				<div id="row">
					<div class="label"><?php echo $this->translate('admin-cp-cover-image'); ?></div>
					<div style="font-size: 15pt;"><?php echo $cover_image; ?></div>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>