<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;

	if ($formdata == null) {
		$formdata['category_id'] = 0;
		$formdata['category_name'] = '';
		$formdata['title'] = '';
		$formdata['brief'] = '';
		$formdata['content'] = '';
		$formdata['duration'] = '';
		$formdata['price'] = '';
		$formdata['start_time'] = '';
		$formdata['start_location'] = '';
		$formdata['tour_path'] = '';
		$formdata['homepage'] = 0;
		$formdata['cover_image'] = '';
		$formdata['publish'] = 1;
		$formdata['lock_status'] = 1;
		$formdata['order'] = 0;
		$formdata['created_by'] = '';
		$formdata['created_time'] = '0000-00-00 00:00:00';
		$formdata['last_modified_by'] = '';
		$formdata['last_modified_time'] = '0000-00-00 00:00:00';
		$formdata['publish_by'] = '';
		$formdata['publish_time'] = '0000-00-00 00:00:00';
		$formdata['hit_counter'] = 0;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$linkTourCat	= $this->baseUrl('/admin/admin-tour-category/info/id/' .$formdata['category_id']);
	$category_name		= '<a href="' . $linkTourCat . '">' . $formdata['category_name'] . '</a>';
	
	$tour_title 	= $formdata['title'];
	$tour_brief 	= $formdata['brief'];
	$tour_content = $formdata['content'];
	$publish		= $formdata['publish'];
	if ($publish == 0) {
		$publish = $this->translate('admin-cw-nopublish');
	} else {
		$publish = $this->translate('admin-cw-publish');
	}
	$order 	= $formdata['order'];
	$tour_homepage = $formdata['homepage'];
	if ($tour_homepage == 0) {
		$tour_homepage = $this->translate('admin-cw-no');
	} else {
		$tour_homepage = $this->translate('admin-cw-yes');
	}
	//----- CREATE: cover image option --------------------------
	$cover_image 	= FILES_URL . '/tour/cover-images/small/' . $formdata['cover_image'];
	$cover_image	= '<img src="' . $cover_image .'"/><br/>';
	
	$arrInput = array(
					array('label'=>$this->translate('admin-tour-add-label-tourcategory'),'input'=>$category_name),
					array('label'=>$this->translate('admin-tour-add-label-tourtitle'),'input'=>$tour_title),
					array('label'=>$this->translate('admin-tour-add-label-tourbrief'),'input'=>$tour_brief),
					array('label'=>$this->translate('admin-tour-add-label-tourcontent'),'input'=>$tour_content,'style'=>'margin-left: 175px;'),
					array('label'=>$this->translate('admin-tour-add-label-coverimage'),'input'=>$cover_image,'style'=>'margin-left: 175px;'),
					array('label'=>$this->translate('admin-cw-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-tour-add-label-homepage'),'input'=>$tour_homepage),
			);
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-tour/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-tour/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>