<?php 
	//----- kiem tra mang lock status. Neu ton tai 1 doi tuong trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	if (isset($this->lockStatus) && !empty($this->lockStatus)) {
		$lockStatus = $this->lockStatus;
	} else {
		$lockStatus = array();
	}
	foreach ($lockStatus as $key=>$val) {
		if ($val['lock_status'] == 1) {
			$alertLockStatus = $this->translate('admin-tour-deletemulti-lockalert');
			echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
		}
	}
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-tour/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-tour/sublink/index.php'); ?>
	<?php 
		if (isset($this->cid)) {
			foreach ($this->cid as $key=>$val) {
				echo $this->formHidden('cid[]',$val); //----- de truyen nguoc lai trang multi-delete
			}
 			echo $this->formHidden('delConfirm',true); //----- de xac nhan du lieu nay duoc gui tu nut Accept
		}
	?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<div id = "errors">
					<?php echo $this->translate('admin-cp-confirm-multidelete'); ?>
				</div>
				
				<?php 
					foreach ($this->Items as $key=>$value) {
						$tour_title = $this->cmsReplaceString($value['title']);
						$cover_image = FILES_URL . '/tour/cover-images/small/' . $value['cover_image'];
						$cover_image = '<img src="' . $cover_image . '"/>';
				?>
				<div id="row" class="delete-row">
					<div class="label"><?php echo $this->translate('admin-tour-add-label-tourtitle'); ?></div>
					<div style="font-size: 15pt;"><?php echo $tour_title . '<br/>' . $cover_image; ?></div>
				</div>
				<?php
					}
				?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>