<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblTourTitle = $this->cmsSortLink('t.title',$this->arrParam,$this->translate('admin-tour-col-tourtitle'),$this->imgUrl,$action_link);
	$lblTourCoverImage = $this->translate('admin-cp-cover-image');
	$lblTourCategory = $this->translate('admin-tour-col-tourcategory');
	$lblTourPublish = $this->cmsSortLink('t.publish',$this->arrParam,$this->translate('admin-cw-publish'),$this->imgUrl,$action_link);
	
	$lblTourPublishTime = $this->cmsSortLink('t.publish_time',$this->arrParam,$this->translate('admin-cp-publishtime'),$this->imgUrl,$action_link);
	$lblTourID = $this->cmsSortLink('t.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblTourOrder = $this->cmsSortLink('t.order',$this->arrParam,$this->translate('admin-cw-order'),$this->imgUrl,$action_link);
	$lblTourLockStatus = $this->cmsSortLink('t.lock_status',$this->arrParam,$this->translate('admin-cp-lockstatus'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: PROJECT CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbTourCat;
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/tourcategory');
	$slbTourCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),
			array('name'=>'category_id','onChange'=>"OnSubmitForm('" .$linkSearch ."')","value"=>$ssFilter['category_id']));
	$selectCategory = 'Tour Category: ' .$slbTourCat;
	
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	$formOrderData = array();
	$formOrderStyle = array();
	if (isset($formdata['order'])) {
		$formOrderData = $formdata['order'];
	}
	if (isset($formstyle['order'])) {
		$formOrderStyle = $formstyle['order'];
	}
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-tour/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-tour/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX - SEARCH AREA----------------------------------->
			<?php echo $errors; ?>
			
			<div id="filters">
				<div style="float: left">
					<?php echo $strSearch; ?>
				</div>

				<div class="clear"></div>
				
				
				
			</div>
			
			

		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		<table class="adminlist">
			<thead>
				<tr>
					<th class="cid">
						<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
					</th>
					<th><?php echo $lblTourTitle; ?></th>
					<th class="col_coverimage"><?php echo $lblTourCoverImage; ?></th>
					<th class="col_article_category"><?php echo $lblTourCategory; ?></th>
					<th class="col_order"><?php echo $lblTourOrder; ?></th>
					<th class="col_publish"><?php echo $lblTourPublish; ?></th>
					<th class="col_publish_time"><?php echo $lblTourPublishTime; ?></th>
					<th class="col_control">Control</th>
					<th class="col_id"><?php echo $lblTourID; ?></th>
					<th class="col_lock_status"><?php echo $lblTourLockStatus; ?></th>
				</tr>
			</thead>
			
			<?php
				
				foreach ($this->Items as $key => $value) {
				$value = $this->cmsReplaceString($value);
					$id = $value['id'];
					$tour_title = $value['title'];
					$cover_image = FILES_URL . '/tour/cover-images/small/' . $value['cover_image'];
					$cover_image = '<img src="' . $cover_image . '"/>';
					$publish = $value['publish'];
					if ($publish == 1) {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/inactive/id/' .$id);
						$publish = $this->cmsIconButton('Stop Publish this Tour',$this->imgUrl .'/icon/active.png',$linkPublish);
					} else {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/active/id/' .$id);
						$publish = $this->cmsIconButton('Publish this Tour',$this->imgUrl .'/icon/inactive.png',$linkPublish);
					}
					
					$lock_status = $value['lock_status'];
					if ($lock_status == 1) {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/inactive/id/' .$id);
						$lock_status = $this->cmsIconButton('This category is locked',$this->imgUrl .'/icon/lockpage.png',$linkLockStatus);
					} else {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/active/id/' .$id);
						$lock_status = $this->cmsIconButton('This category is unlocked',$this->imgUrl .'/icon/unlockpage-black.png',$linkLockStatus);
					}

					$orderStyle = 'width: 30px; text-align: center;';
					if (!empty($formOrderStyle[$value['id']])) {
						$orderStyle .= $formOrderStyle[$value['id']];
					}
					$orderValue = $value['order'];
					if (isset($formOrderData[$value['id']])) {
						$orderValue = $formOrderData[$value['id']];
					}
					//----- neu doi tuong bi khoa thi vo hieu hoa o textbox order
					if ($value['lock_status'] == 0) {
						$order = $this->formText('order[' .$value['id'] .']',$orderValue,
								array('style'=> $orderStyle));
					} else if ($value['lock_status'] == 1) {
						$order = $this->formText('order[' .$value['id'] .']',$orderValue,
								array('style'=> $orderStyle,'disabled'=>true));
					}
					
					//----- chuyen publish_time tu dang Y-m-d sang d-m-Y de hien thi ra view
					$publish_time = date('d-m-Y H:s:m',strtotime($value['publish_time']));
					
					$category_id = $value['category_id'];
					$categoryLink = $this->baseUrl('/admin/admin-tour-category/info/id/' . $category_id);
					$category_name = $value['category_name'];
					$strTourCategory = '<a href="' . $categoryLink . '">' . $category_name . '</a>';
					
					$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
					$btnInfo = $this->cmsIconButton('View information',$this->imgUrl .'/icon/icon_info.png',$linkInfo);
					$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
					$btnEdit = $this->cmsIconButton('Edit Item',$this->imgUrl .'/icon/icon_edit.png',$linkEdit);
					$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
					$btnDelete = $this->cmsIconButton('Delete Item',$this->imgUrl .'/icon/icon_del.png',$linkDelete);
					$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
					
					$cid = $this->formCheckbox('cid[]',$value['id']);
			?>
			
			<tr class="even">						
					<td align="center"><?php echo $cid; ?></td>
					<td align="left"><?php echo $tour_title; ?></td>
					<td align="center"><?php echo $cover_image; ?></td>
					<td align="center"><?php echo $strTourCategory; ?></td>
					<td align="center"><?php echo $order; ?></td>
					<td align="center"><?php echo $publish; ?></td>
					<td align="center"><?php echo $publish_time; ?></td>
					<td align="center">
						<?php echo $strControlIconButton; ?>
					</td>
					<td align="center"><?php echo $id; ?></td>
					<td align="center"><?php echo $lock_status; ?></td>
			</tr>
			
			<?php 
				} // ------------- dong vong lap foreach ----------------
			?>
	<!--------------------------------------- BEGIN: PAGINATION (FOOT) --------------------------------------->
			<tfoot>
				<tr>
					<td colspan="11">
						<div class="container">
							<div class="pagination">
								<div class="limit">Display #
									<select onchange="submitform();" size="1" class="inputbox" id="limit" name="limit">
										<option value="5">5</option>
									</select>
								</div>
								<div class="limit">
									<?php $currentUrl = $this->baseUrl($this->currentController . '/index'); ?>
									<?php echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); ?>
								</div>
								<div class="limit"></div>
							</div>
						</div>
					</td>
				</tr>					
			</tfoot>				
	<!--------------------------------------- END: PAGINATION (FOOT) --------------------------------------->
		</table>
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>