<div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

        		<!-- Categories -->
        		<div class="col-lg-12 col-md-12 col-sm-6">
	        		<div class="no-padding">
	            		<span class="title"><br></span>
	            	</div>

					<div class="list-group list-categ">
						<a href="catalogue.html" class="list-group-item">Góc khuyến nông</a>
						<a href="catalogue.html" class="list-group-item">Góc sinh thái </a>
						<a href="catalogue.html" class="list-group-item">Góc ẩm thực</a>
						<a href="catalogue.html" class="list-group-item">Góc sưc khỏe </a>
					</div>

				</div>
				<!-- End Categories -->



        	</div>

        <div class="clearfix visible-sm"></div>

			<!-- Featured -->
       <div class="col-lg-9 col-md-9 col-sm-12">
			<div class="col-lg-12 col-sm-12 col-md-12">
            		<span class="title" style="font-size:28px;color:#c64d06">PHẢN HỒI TỪ KHÁCH HÀNG</span>
					
            	</div>

				<div class="item ykh">
					<h4>
<p>Nguyễn Thế Anh | giahung2009dh@gmail.com </p>
<p>Xin chào!</p>
<h5>Tôi cũng là khách hàng mới của cty bạn, các bạn có web rất đẹp dịch vụ rất tốt. Tôi rất đam mê chơi gà gia đình tôi nuôi gà để phục vụ thú chơi và nhu cầu thực phẩm cho gia đình thôi. Vừa qua tôi có mua ít gà đông tảo của cty nhưng tôi cảm thấy các bạn cần tiếp tục làm tốt hơn nữa những gì mà các bạn đã giới thiệu ở web. Hiện bạn bè và người dân sống gần tôi đến liên hệ nhờ đặt mua ít gà đông tảo về nuôi. Năm mới tôi chúc quý cty sức khoẻ thành đạt và mãi mãi là địa chỉ uy tín của khách hàng.</h5></h4><hr>
<h4>
<p>Nguyễn Thế Anh | giahung2009dh@gmail.com </p>
<p>Xin chào!</p>
<h5>Tôi cũng là khách hàng mới của cty bạn, các bạn có web rất đẹp dịch vụ rất tốt. Tôi rất đam mê chơi gà gia đình tôi nuôi gà để phục vụ thú chơi và nhu cầu thực phẩm cho gia đình thôi. Vừa qua tôi có mua ít gà đông tảo của cty nhưng tôi cảm thấy các bạn cần tiếp tục làm tốt hơn nữa những gì mà các bạn đã giới thiệu ở web. Hiện bạn bè và người dân sống gần tôi đến liên hệ nhờ đặt mua ít gà đông tảo về nuôi. Năm mới tôi chúc quý cty sức khoẻ thành đạt và mãi mãi là địa chỉ uy tín của khách hàng.</h5></h4>
<h4>
<p>Hòa Bình có nhiều đặc sản đủ thỏa mãn mọi giác quan, ở đây xin được giới thiệu một số thứ tiêu biểu:</p>
<strong>1. Lợn lửng:</strong> <h5>Còn được gọi là lợn Mán, lợn tộc, lợn Mường… Tôi thì thích gọi cái tên này vì con lợn không to chẳng bé, nuôi thả bán hoang dã, có gì ăn nấy nên vị thịt ngọt tự nhiên và có vị thơm dịu, nhất là đến mỡ cũng thơm. Các món chế từ lợn lửng hàng đầu phải kể đến: Tiết canh, lòng xe điếu, thịt luộc chấm muối rang cùng hạt dổi nướng giã nhỏ, chả nướng… Và các món luộc, nướng này mà bày lên mâm tre lót lá chuối kèm theo nhiều thứ rau sống thì tuyệt nhất. Món chế ăn sẵn từ thịt lợn lửng Hòa Bình thì kiếm thịt chua, còn gọi là thịt dưa, cũng gặp nhiều ở vùng Thanh Sơn, Phú Thọ.</h5>
</h4>
<h4>
<p>Hòa Bình có nhiều đặc sản đủ thỏa mãn mọi giác quan, ở đây xin được giới thiệu một số thứ tiêu biểu:</p>
<strong>1. Lợn lửng:</strong> <h5>Còn được gọi là lợn Mán, lợn tộc, lợn Mường… Tôi thì thích gọi cái tên này vì con lợn không to chẳng bé, nuôi thả bán hoang dã, có gì ăn nấy nên vị thịt ngọt tự nhiên và có vị thơm dịu, nhất là đến mỡ cũng thơm. Các món chế từ lợn lửng hàng đầu phải kể đến: Tiết canh, lòng xe điếu, thịt luộc chấm muối rang cùng hạt dổi nướng giã nhỏ, chả nướng… Và các món luộc, nướng này mà bày lên mâm tre lót lá chuối kèm theo nhiều thứ rau sống thì tuyệt nhất. Món chế ăn sẵn từ thịt lợn lửng Hòa Bình thì kiếm thịt chua, còn gọi là thịt dưa, cũng gặp nhiều ở vùng Thanh Sơn, Phú Thọ.</h5>
</h4>
<h4>
<p>Hòa Bình có nhiều đặc sản đủ thỏa mãn mọi giác quan, ở đây xin được giới thiệu một số thứ tiêu biểu:</p>
<strong>1. Lợn lửng:</strong> <h5>Còn được gọi là lợn Mán, lợn tộc, lợn Mường… Tôi thì thích gọi cái tên này vì con lợn không to chẳng bé, nuôi thả bán hoang dã, có gì ăn nấy nên vị thịt ngọt tự nhiên và có vị thơm dịu, nhất là đến mỡ cũng thơm. Các món chế từ lợn lửng hàng đầu phải kể đến: Tiết canh, lòng xe điếu, thịt luộc chấm muối rang cùng hạt dổi nướng giã nhỏ, chả nướng… Và các món luộc, nướng này mà bày lên mâm tre lót lá chuối kèm theo nhiều thứ rau sống thì tuyệt nhất. Món chế ăn sẵn từ thịt lợn lửng Hòa Bình thì kiếm thịt chua, còn gọi là thịt dưa, cũng gặp nhiều ở vùng Thanh Sơn, Phú Thọ.</h5>
</h4><hr>
				</div>
			<div class="col-lg-12 col-sm-12 col-md-12">
            		<span class="title" style="font-size:28px;color:#c64d06">Ý kiến khách hàng</span>
					
            	</div>
        		

		
<div class="item ykh">
	<?php
	if(isset($this->Items)){
		foreach ($this->Items as $key => $value) {
  $email=$value['email'];
  $name=$value['name'];
  $comment=$value['comment'];
  $time=$value['post_time'];
  ?>
	<h4>
		<p>
			<?php echo $name;?>
			|
			<?php echo $email;?>
		</p>
		<?php echo $comment;?>
		Vào ngày:
		<?php echo $time;?>
	</h4>
	<hr>

	<?php
  }
	}
	?>




</div>


<form role="form" class="contact-form" method="post" action="">
	<div class="item">

		<?php
		$errors = '';
		if (count($this->messageError) > 0) {
    $errors = $this->formErrors($this->messageError,array('id'=>'contact_errors'));
  }
  if(!empty($errors)) {
                if($this->validateResult == "error") {
          ?>
		<div class="alert alert-danger">
			<?php echo $errors; ?>
		</div>
		<?php } else if($this->validateResult == "success") { 
			?>
		<div class="alert alert-success">
			<?php echo $errors; ?>
		</div>
		<?php 
		}
              }
              ?>
		<div class="fields">
			<label class="required " for="Contact_name">Tên <span class="required">(*)</span></label> 
			<input type="text" id="name" name="name" class="form-control">
		</div>

		<div class="fields">
			<label class="required" for="Contact_email">Email <span class="required">(*)</span>
			</label> <input type="text" id="email" name="email" class="form-control">
		</div>

		<div class="fields">
			<label class="required" for="Contact_body">Nội dung <span class="required">(*)</span></label>
			<textarea name="comment" rows="8" cols="5" id="comment" class="form-control"></textarea>
		</div>

		<div class="buttons">
			<input type="submit" value="Gửi đi" class="guidi pull-right">
		</div>

		

	</div>
</form>

      	</div>
        	
        	
    <div class="clearfix visible-sm"></div>

</div>