<?php
$ssFilter = $this->arrParam['ssFilter'];
$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
$curControllerLink = $this->baseUrl($this->currentController);

$lblProductName = $this->cmsSortLink('p.product_name',$this->arrParam,$this->translate('admin-product-add-label-productname'),$this->imgUrl,$action_link);
$lblProductCoverImage = $this->translate('admin-cp-cover-image');

$lblProductPublish = $this->cmsSortLink('p.publish',$this->arrParam,$this->translate('admin-cw-publish'),$this->imgUrl,$action_link);
$lblProductPublishTime = $this->cmsSortLink('p.publish_time',$this->arrParam,$this->translate('admin-cp-publishtime'),$this->imgUrl,$action_link);

$lblProductOrder = $this->cmsSortLink('p.order',$this->arrParam,$this->translate('admin-cw-order'),$this->imgUrl,$action_link);

$lblProductCategory = $this->cmsSortLink('pc.category_name',$this->arrParam,$this->translate('admin-product-add-label-categoryname'),$this->imgUrl,$action_link);
$lblProductID = $this->cmsSortLink('p.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
$lblProductLockStatus = $this->cmsSortLink('p.lock_status',$this->arrParam,$this->translate('admin-cp-lockstatus'),$this->imgUrl,$action_link);

//--------------------------------------- CREATE: PRODUCT CATEGORY SELECT BOX --------------------------
$sourceArr = $this->slbProCat;
$linkSearch = $this->baseUrl($this->currentController . '/filter/type/productcategory');
$slbProCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),
		array('name'=>'product_category_id','onChange'=>"OnSubmitForm('" .$linkSearch ."')","value"=>$ssFilter['product_category_id']));
$selectGroup = 'Product Category: ' .$slbProCat;

//--------------------------------------- CREATE: SEARCH AREA -------------------------------
$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');

$btnSearch 		= $this->formButton('search-now','Search',
		array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
$btnResetSearch = $this->formButton('clear-keywords','Clear',
		array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;

?>
<div class="row">
	<div class="col-lg-12">
		<div id="toolbar-box">
			<div class="t">
				<div class="t">
					<div class="t"></div>
				</div>
			</div>
			
			<div class="m">
				
				<h3 class="page-header">Order :: Order manager :: List</h3>
		                                
				<div class="clr"></div>
			</div>
			<div class="b">
				<div class="b">
					<div class="b"></div>
				</div>
			</div>
		</div>
	</div>
</div>
<form
	name="appForm" method="post" action="">
	<?php //echo $this->render('/admin-product/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-product/sublink/index.php'); ?>

	<!-- ------------------------------------ table Admin verion 2 ------------------------- -->
	<div class="panel panel-default adminlist">
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover"
					id="dataTables-object">
					<thead>
						<tr>
							<th class="col_cid"><input type="checkbox" name="checkbox"
								id="checkbox" onclick="checkedAll()">
							</th>
							<th>Order ID</th>
							<th>Tên khách hàng</th>

							<th class="col_procat_name">Email</th>
							<th class="col_order">Mobile</th>
							<th class="col_publish">Địa chỉ</th>
							<th class="col_publish_time">Thông tin thêm</th>
							<th class="col_publish_time">Ngày đặt hàng</th>
							<th class="col_publish_time">Hạn giao hàng</th>
							<th class="col_publish_time">Tổng tiền</th>
							<th class="col_publish_time">Trạng thái</th>

							<th class="col_control">Control</th>

						</tr>
					</thead>
					<tbody>

						<?php //var_dump($this->Items);
foreach ($this->Items as $key => $value) {
							$value = $this->cmsReplaceString($value);
							$id = $value['id'];
							$customer_name = $value['name'];
							$mobile = $value['mobile'];
							$email = $value['email'];
							$information = $value['information'];
							$total= $value['total'];
							$status= $value['status'];
							if($status=='O'){
								$slb_status='<select  onchange="changestatus(this.value,'.$id.',\'O\')">
		<option value="O" selected="selected">News</option>
		<option value="D">Delete</option>
		</select>';
							}else{
								$slb_status='<select  onchange="changestatus(this.value,'.$id.',\'D\')">
		<option value="O" >News</option>
		<option value="D" selected ="selected">Delete</option>
		</select>';
							}

							$address=$value['address'];
							$created_time	= date('d/m/Y H:i:s',strtotime($value['created_time']));
							$limit_time	= 'dang test';//date('d/m/Y H:i:s',strtotime($value['created_time']));
							/*
							 //----- lay thong so lock_status
							$lock_status = $value['lock_status'];
							if ($lock_status == 1) {
								$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/inactive/id/' .$id);
							$lock_status = $this->cmsIconButton('Unlock this Product','fa fa-lock',$linkLockStatus,'css');
							} else {
								$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/active/id/' .$id);
							$lock_status = $this->cmsIconButton('Lock this Product','fa fa-unlock',$linkLockStatus,'css');
							}

							//----- neu doi tuong bi khoa thi vo hieu hoa o textbox order
							if ($value['lock_status'] == 0) {
								$order = $this->formText('order[' .$value['id'] .']',$value['order'],
										array('style'=> 'width: 30px; text-align: center;'));
							} else if ($value['lock_status'] == 1) {
								$order = $this->formText('order[' .$value['id'] .']',$value['order'],
										array('style'=> 'width: 30px; text-align: center;','disabled'=>true));
										}

										$category_id = $value['product_category_id'];
										$categoryLink = $this->baseUrl('/admin/admin-product-category/info/id/' . $category_id);
										$category_name = $value['category_name'];
										$strProductCategory = '<a href="' . $categoryLink . '">' . $category_name . '</a>';
										*/
							$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
							$btnInfo = $this->cmsIconButton('View information','fa fa-info-circle fa-lg',$linkInfo,'css');
							$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
							$btnEdit = $this->cmsIconButton('Edit Item','fa fa-edit fa-lg',$linkEdit,'css');
							$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
							$btnDelete = $this->cmsIconButton('Delete Item','fa fa-times-circle fa-lg',$linkDelete,'css');

							$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;

							$cid = $this->formCheckbox('cid[]',$value['id']);
							?>

						<tr class="odd gradeX even">
							<td align="center"><?php echo $cid; ?></td>
							<td align="center"><?php echo $id; ?></td>
							<td align="left"><?php echo $customer_name; ?></td>
							<td align="center"><?php echo $email; ?></td>
							<td align="center"><?php echo $mobile; ?></td>
							<td align="center"><?php echo $address; ?></td>
							<td align="center"><?php echo $information; ?></td>
							<td align="center"><?php echo $limit_time; ?></td>
							<td align="center"><?php echo $created_time; ?></td>

							<td align="center"><?php echo $total; ?></td>
							<td align="center"><?php echo $slb_status; ?></td>
							<td align="center"><?php echo $strControlIconButton; ?> <?php //echo $strControlIconButton; ?>
							</td>
						</tr>

						<?php 
				} // ------------- dong vong lap foreach ----------------
				?>

					</tbody>
				</table>
			</div>
			<!-- /.table-responsive -->
		</div>
		<!-- /.panel-body -->
	</div>
	<!-- -------------------------------- End table Admin verion 2 ------------------------- -->



</form>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script type="text/javascript">
function changestatus(next_status,order_id,pre_status){
alert(next_status+order_id+pre_status);
$.ajax({
      url: '/shop-np/admin/ajax/changestatus',
      type: 'post',
      data: {'next_status':next_status,'order_id':order_id,'pre_status':pre_status},
      cache: false,
      success: function(json) {//alert(json);
      
      },
      error: function(xhr, desc, err) {
        console.log(xhr + "\n" + err);
      }
    });
}
</script>
<script>
    //$(document).ready(function() {
       // $('#dataTables-object').dataTable();
   // });
</script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-object').dataTable();
    });
</script>
