<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblCategoryName = $this->cmsSortLink('tc.category_name',$this->arrParam,$this->translate('admin-tourcategory-col-categoryname'),$this->imgUrl,$action_link);
	$lblCategoryID = $this->cmsSortLink('tc.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblCategoryDesc = $this->cmsSortLink('tc.description',$this->arrParam,$this->translate('admin-cw-description'),$this->imgUrl,$action_link);
	$lblCategoryPublish = $this->cmsSortLink('tc.publish',$this->arrParam,$this->translate('admin-cw-publish'),$this->imgUrl,$action_link);
	$lblCategoryPublishTime = $this->cmsSortLink('tc.publish_time',$this->arrParam,$this->translate('admin-cp-publishtime'),$this->imgUrl,$action_link);
	$lblCategoryOrder = $this->cmsSortLink('tc.order',$this->arrParam,$this->translate('admin-cw-order'),$this->imgUrl,$action_link);
	$lblCategoryLockStatus = $this->cmsSortLink('tc.lock_status',$this->arrParam,$this->translate('admin-cp-lockstatus'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->OrderErrorMessage) > 0) {
		$errors = $this->formErrors($this->OrderErrorMessage,array('id'=>'errors'));
	}
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-tour-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-tour-category/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX - SEARCH AREA----------------------------------->
			<?php echo $errors; ?>
			
			<div id="filters">
				<div style="float: left">
					<?php echo $strSearch; ?>
				</div>

				<div class="clear"></div>
				
				
				
			</div>
			
			

		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		<table class="adminlist">
			<thead>
				<tr>
					<th width="43" >
						<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
					</th>
					<th><?php echo $lblCategoryName; ?></th>
					<th class="col_newscat_desc"><?php echo $lblCategoryDesc; ?></th>
					<th class="col_order"><?php echo $lblCategoryOrder; ?></th>
					<th class="col_publish"><?php echo $lblCategoryPublish; ?></th>
					<th class="col_publish_time"><?php echo $lblCategoryPublishTime; ?></th>
					<th class="col_control">Control</th>
					<th class="col_id"><?php echo $lblCategoryID; ?></th>
					<th class="col_lock_status"><?php echo $lblCategoryLockStatus; ?></th>
				</tr>
			</thead>
			
			<?php
				$OrderErrorStyle 	= $this->OrderErrorStyle;
				$OrderErrorData 	= $this->OrderErrorData;
				
				//----- sap xep lai danh sach cac category theo quan he cha-con, dua vao mang $newArray
				$sourceArr = $this->Items;
				$objRecursive = new Zendvn_System_Recursive();
				$newArray = array();
				$objRecursive->recursive($sourceArr, 0, 1, $newArray);
				
				foreach ($newArray as $key => $value) {
					$value = $this->cmsReplaceString($value);
					$id = $value['id'];
					
					$category_name = $value['category_name'];
					if ($value['level'] == 1) {
						$category_name = $value['category_name'];
					} else {
						$string = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
						$string = '- - - - - ';
						$newString = '';
						for ($i=1; $i< $value['level']; $i++) {
							$newString .= $string;
						}
						$category_name = $newString .$value['category_name'];
					}
					
					$description = $value['description'];
					
					$lock_status = $value['lock_status'];
					if ($lock_status == 1) {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/inactive/id/' .$id);
						$lock_status = $this->cmsIconButton('This page is locked',$this->imgUrl .'/icon/lockpage.png',$linkLockStatus);
					} else {
						$linkLockStatus = $this->baseUrl($this->currentController .'/change-lock-status/type/active/id/' .$id);
						$lock_status = $this->cmsIconButton('This page is unlocked',$this->imgUrl .'/icon/unlockpage-black.png',$linkLockStatus);
					}
					//----- neu doi tuong bi khoa thi vo hieu hoa o textbox order
					if ($value['lock_status'] == 0) {
						$order = $this->formText('order[' .$value['id'] .']',$value['order'],
								array('style'=> 'width: 30px; text-align: center;'));
					} else if ($value['lock_status'] == 1) {
						$order = $this->formText('order[' .$value['id'] .']',$value['order'],
								array('style'=> 'width: 30px; text-align: center;','disabled'=>true));
					}
					
					$publish = $value['publish'];
					if ($publish == 1) {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/inactive/id/' .$id);
						$publish = $this->cmsIconButton('Stop Publish this Tour Category',$this->imgUrl .'/icon/active.png',$linkPublish);
					} else {
						$linkPublish = $this->baseUrl($this->currentController .'/publish/type/active/id/' .$id);
						$publish = $this->cmsIconButton('Publish this Tour Category',$this->imgUrl .'/icon/inactive.png',$linkPublish);
					}
					//----- chuyen publish_time tu dang Y-m-d sang d-m-Y de hien thi ra view
					$publish_time = date('d-m-Y H:s:m',strtotime($value['publish_time']));
					
					$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
					$btnInfo = $this->cmsIconButton('View information',$this->imgUrl .'/icon/icon_info.png',$linkInfo);
					$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
					$btnEdit = $this->cmsIconButton('Edit Item',$this->imgUrl .'/icon/icon_edit.png',$linkEdit);
					$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
					$btnDelete = $this->cmsIconButton('Delete Item',$this->imgUrl .'/icon/icon_del.png',$linkDelete);
					$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
					
					$cid = $this->formCheckbox('cid[]',$value['id']);
			?>
			
			<tr class="even">						
					<td align="center"><?php echo $cid; ?></td>
					<td align="left"><?php echo $category_name; ?></td>
					<td align="center"><?php echo $description; ?></td>
					<td align="center"><?php echo $order; ?></td>
					<td align="center"><?php echo $publish; ?></td>
					<td align="center"><?php echo $publish_time; ?></td>
					<td align="center">
						<?php echo $strControlIconButton; ?>
					</td>
					<td align="center"><?php echo $id; ?></td>
					<td align="center"><?php echo $lock_status; ?></td>
			</tr>
			
			<?php 
				} // ------------- dong vong lap foreach ----------------
			?>
	<!--------------------------------------- BEGIN: PAGINATION (FOOT) --------------------------------------->
			<tfoot>
				<tr>
					<td colspan="10">
						<div class="container">
							<div class="pagination">
								<div class="limit">Display #
									<select onchange="submitform();" size="1" class="inputbox" id="limit" name="limit">
										<option value="5">5</option>
									</select>
								</div>
								<div class="limit">
									<?php $currentUrl = $this->baseUrl($this->currentController . '/index'); ?>
									<?php echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); ?>
								</div>
								<div class="limit"></div>
							</div>
						</div>
					</td>
				</tr>					
			</tfoot>				
	<!--------------------------------------- END: PAGINATION (FOOT) --------------------------------------->
		</table>
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>