<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;
	$memberCount = $this->memberCount;
	$childCount = $this->childCount;

	if ($memberCount == 0) {
		$strMemberCount = $this->translate('admin-tourcategory-info-nonews');
	} else {
		$strMemberCount = '<span style="font-size: 15pt;">' .$memberCount .'</span>' . $this->translate('admin-tourcategory-info-havenews');
	}
	if ($childCount == 0) {
		$strChildCount = $this->translate('admin-tourcategory-info-nochild');
	} else {
		$strChildCount = '<span style="font-size: 15pt;">' .$childCount .'</span>' . $this->translate('admin-tourcategory-info-havechild');
	}
	/* if (count($memberList) > 0) {
		//----- nhom co thanh vien
		$linkMemberList = $memberCount;
		foreach($memberList as $key=>$val) {
			$user_id = $val['id'];
			$user_name = $val['user_name'];
			$linkUserInfo = $this->baseUrl('/admin/admin-user/info/id/' .$user_id);
			$style = 'margin: 5px; padding: 1px 5px; background-color: #d8d8d8;';
			$linkMemberList .= '<a style="' . $style . '" href="' . $linkUserInfo . '">' . $user_name . '  ' . '</a>';		
		}
	} else {
		//----- nhom khong co thanh vien
		$linkMemberList = 'This group has no member';
	} */
	if ($formdata == null) {
		$formdata['category_name'] = '';
		$formdata['description'] = 0;
		$formdata['publish'] = 1;
		$formdata['order'] = 1;
		$formdata['created_by'] = 0;
		$formdata['created'] = '';
		$formdata['user_id'] = 0;
		$formdata['user_name'] = '';
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$category_name 	= $formdata['category_name'];
	$description 	= $formdata['description'];
	$order			= $formdata['order'];
	//----- chuyen created tu dang Y-m-d sang d-m-Y de hien thi ra view
	$created 		= date('d-m-Y',strtotime($formdata['created']));
	$created_by		= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['user_id']) . '">' . $formdata['user_name'] . '</a>';
	$publish		= $formdata['publish'];
	if ($publish == 0) {
		$publish 	= $this->translate('admin-cw-nopublish');
	} else {
		$publish 	= $this->translate('admin-cw-publish');
	}	
	
	$arrInput = array(
					array('label'=>$this->translate('admin-newscategory-col-categoryname'),'input'=>$category_name,'style'=>'font-size: 15pt;'),
					array('label'=>$this->translate('admin-cw-description'),'input'=>$description),
					array('label'=>$this->translate('admin-cw-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-cp-createdby'),'input'=>$created_by),
					array('label'=>$this->translate('admin-cp-createdtime'),'input'=>$created),
					array('label'=>$this->translate('admin-tourcategory-info-totaltour'),'input'=>$strMemberCount),
					array('label'=>$this->translate('admin-tourcategory-info-totalchild'),'input'=>$strChildCount),
			);	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-tour-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-tour-category/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>