<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['group_privilege_id'] = 0;
		$formdata['group_id'] = 0;
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['group_privilege_id'] = 'min-width: 200px';
		$formstyle['group_id'] = 'min-width: 200px';
	}
	
	//----- CREATE: GROUP SELECT BOX --------------------------
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/group');
	$options = $this->slbGroup;
	$slbGroup = $this->formSelect('group_id',$formdata['group_id'],array('style'=>$formstyle['group_id'],
							'onchange'=>"OnSubmitForm('" .$linkSearch ."')"),$options);
	
	//----- CREATE: PRIVILEGE SELECT BOX --------------------------
	$options = $this->slbPrivilege;
	$slbPrivilege = $this->formSelect('group_privilege_id',$formdata['group_privilege_id'],array('style'=>$formstyle['group_privilege_id'],'size'=>10,'multiple'=>true),$options);
	
	$arrInput = array(
					array('label'=>$this->translate('admin-cw-group'),'input'=>$slbGroup),
					array('label'=>$this->translate('admin-cw-privilege'),'input'=>$slbPrivilege),
					
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-permission/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-permission/sublink/index.php'); ?>

	<?php echo $errors; ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>