<?php 
	$privilege_name 	= $this->Item['name'];
	$group_name 		= $this->group_name;
	$group_name_style = 'display: inline; margin: 5px; padding: 1px 5px; background-color: #d8d8d8; font-size: 14pt;';
	//----- thong bao loi -----
	$errors = '';
	$messageError = $this->messageError;
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-permission/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-permission/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				
				<div id = "errors">
					<?php echo $this->translate('admin-privilege-delete-confirm'); ?>
				</div>
				
				<div id="row">
					<div class="label">Group Name:</div>
					<div style="<?php echo $group_name_style ?>"><?php echo $group_name; ?></div>
				</div>
				
				<div id="row">
					<div class="label">Privilege Name:</div>
					<div style="font-size: 15pt;"><?php echo $privilege_name; ?>
						<?php if (!empty($messageError)) { ?>
							<div id = "errors" style="margin-top: 8px;">
								<?php echo $messageError; ?>
							</div>
						<?php } ?>
					</div>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>