<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblPrivilegeName = $this->cmsSortLink('p.name',$this->arrParam,$this->translate('admin-privilege-col-privilegename'),$this->imgUrl,$action_link);
	
	$lblPrivilegeID = $this->cmsSortLink('gp.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblPrivilegeStatus = $this->cmsSortLink('gp.status',$this->arrParam,$this->translate('admin-cw-status'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: GROUP SELECT BOX --------------------------
	$options = $this->slbGroup;
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/group');
	$slbGroup = $this->formSelect('group_id',$ssFilter['group_id'],
							array('onchange'=>"OnSubmitForm('" .$linkSearch ."')"),$options);
	$selectGroup = 'Group: ' . $slbGroup;
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-permission/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php echo $this->render('/admin-permission/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
		<!--------------------------------------- BEGIN: ELEMENT BOX ----------------------------------->
			<div id="filters">
				<div style="float: left">
					<?php //echo $strSearch; ?>
				</div>
				<div style="float: right">
					<?php echo $selectGroup; ?>
				</div>
				<div class="clear"></div>
			</div>

		<!--------------------------------------- Area 4: In du lieu lay tu database ------------------->
		<table class="adminlist">
			<thead>
				<tr>
					<th class="col_cid">
						<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
					</th>
					<th><?php echo $lblPrivilegeName; ?></th>
					<th class="col_control_privilege">Control</th>
					<th class="col_id"><?php echo $lblPrivilegeID; ?></th>
				</tr>
			</thead>
			
			<?php 
				foreach ($this->Items as $key => $value) {

					$id = $value['id'];
					$privilege_id = $value['privilege_id'];
					$privilege_name = $value['name'];
					$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
					$btnInfo = $this->cmsIconButton('View information',$this->imgUrl .'/icon_info.png',$linkInfo);
					$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
					$btnEdit = $this->cmsIconButton('Edit Item',$this->imgUrl .'/icon_edit.png',$linkEdit);
					
					$privilege_type = $value['privilege_type'];
					if ($privilege_type == 'direct_privilege') {
						$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
						$btnDelete = $this->cmsIconButton('Delete Item',$this->imgUrl .'/icon/icon_del.png',$linkDelete);
						$strControlIconButton = $btnDelete;
					} else if ($privilege_type == 'inherit_privilege') {
						$parent_group_id = $value['group_id'];
						$parent_group_name = $value['group_name'];
						$parent_group_url = $this->baseUrl('/admin/admin-group/info/id/' . $parent_group_id);
						$parent_group_link = '<a style="font-weight: bold;" href="' . $parent_group_url . '">' . $parent_group_name . '</a>';
						$strControlIconButton = $this->translate('admin-cp-inherit-from') .$parent_group_link;
					}
					
					
					$cid = $this->formCheckbox('cid[]',$value['id']);
			?>
			
			<tr class="even">						
					<td align="center"><?php echo $cid; ?></td>
					<td align="left"><?php echo $privilege_name; ?></td>
					<td align="center">
						<?php echo $strControlIconButton; ?>
					</td>
					<td align="center"><?php echo $id; ?></td>
			</tr>
			
			<?php 
				} // ------------- dong vong lap foreach ----------------
			?>
	<!--------------------------------------- BEGIN: PAGINATION (FOOT) --------------------------------------->
			<tfoot>
				<tr>
					<td colspan="9">
						<div class="container">
							<div class="pagination">
								<div class="limit">Display #
									<select onchange="submitform();" size="1" class="inputbox" id="limit" name="limit">
										<option value="5">5</option>
									</select>
								</div>
								<div class="limit">
									<?php $currentUrl = $this->baseUrl($this->currentController . '/index'); ?>
									<?php echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); ?>
								</div>
								<div class="limit"></div>
							</div>
						</div>
					</td>
				</tr>					
			</tfoot>				
	<!--------------------------------------- END: PAGINATION (FOOT) --------------------------------------->
		</table>
	<!--------------------------------------- END Area 4: In du lieu lay tu database ------------------->		                                

	<!--------------------------------------- END: ELEMENT BOX ----------------------------------->
                              <div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>