<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['product_category_id'] = 0;
		$formdata['product_name'] = '';
		$formdata['product_serial'] = '';
		$formdata['price'] = '';
		$formdata['product_detail'] = '';
		$formdata['cover_image'] = '';

		$formdata['product_assessment'] = '';

		$formdata['product_guarantee'] = '';
		
		$formdata['product_model'] = '';
		
		$formdata['product_code'] = '';
		$formdata['product_guarantee_policy'] = '';
		$formdata['product_price_new'] = '';
		$formdata['view_counter'] = '';

		$formdata['publish'] = 1;
		$formdata['lock_status'] = 1;
		$formdata['order'] = $this->lastProductOrder + 1;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['product_name'] = '';
		$formstyle['product_serial'] = '';
		$formstyle['price'] = '';
		$formstyle['product_detail'] = '';
		$formstyle['product_category_id'] = 'min-width: 200px';
		$formstyle['cover_image'] = '';

		$formstyle['product_assessment'] = '';
		
		$formstyle['product_guarantee'] = '';
		
		$formstyle['product_model'] = '';
		
		$formstyle['product_code'] = '';
		$formstyle['product_guarantee_policy'] = '';
		$formstyle['product_price_new'] = '';
		$formstyle['view_counter'] = '';

		$formstyle['order'] = '';
	}
	//----- CREATE: PRODUCT CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbProCat;
	$slbProCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),array('name'=>'product_category_id',
							'value'=>$formdata['product_category_id'],'style'=>$formstyle['product_category_id']));
	
	$product_name 	= $this->formText('product_name',$formdata['product_name'],array('class'=>'form-control','style'=>$formstyle['product_name']));
	$product_serial	= $this->formText('product_serial',$formdata['product_serial'],array('class'=>'form-control','style'=>$formstyle['product_serial']));
	$price		 	= $this->formText('price',$formdata['price'],array('class'=>'txtshort','style'=>$formstyle['price']));
	$product_detail = $this->cmsEditor('product_detail',$formdata['product_detail'],array('toolbar'=>'FullToolbar'),array('class'=>'form-control'));
	$cover_image 	= $this->formFile('cover_image',array('style'=>$formstyle['cover_image'])) .' (recommend image size: 288px-208px)';
	//var_dump($formdata);
	//var_dump($formstyle);

	$product_assessment = $this->cmsEditor('product_assessment',$formdata['product_assessment'],array('toolbar'=>'FullToolbar'),array('class'=>'form-control'));
	
	$product_guarantee	= $this->formText('product_guarantee',$formdata['product_guarantee'],array('class'=>'form-control','style'=>$formstyle['product_guarantee']));

	$product_model	= $this->formText('product_model',$formdata['product_model'],array('class'=>'form-control','style'=>$formstyle['product_model']));
		
	$product_code	= $this->formText('product_code',$formdata['product_code'],array('class'=>'form-control','style'=>$formstyle['product_code']));
	$product_guarantee_policy = $this->cmsEditor('product_guarantee_policy',$formdata['product_guarantee_policy'],array('toolbar'=>'FullToolbar'),array('class'=>'form-control'));
	$product_price_new = $this->formText('product_price_new',$formdata['product_price_new'],array('class'=>'txtshort','style'=>$formstyle['product_price_new']));
	$view_counter = $this->formText('view_counter',$formdata['view_counter'],array('class'=>'txtshort','style'=>$formstyle['view_counter']));

	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-product_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->FormData['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-product-add-publish-warning') . $this->formHidden('publish',0);
	}
	
	//----- CREATE: lock status option --------------------------
	if (in_array('admin_admin-product_change-lock-status', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->FormData['lock_status'] = 0;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-product-add-lockstatus-warning') . $this->formHidden('lock_status',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	//$view_counter 	= $this->formText('view_counter',$formdata['view_counter'],array('class'=>'txtshort','style'=>$formstyle['view_counter']));
	$arrInput = array(
					array('label'=>$this->translate('admin-product-add-label-categoryname'),'input'=>$slbProCat),
					array('label'=>$this->translate('admin-product-add-label-productname'),'input'=>$product_name),
					array('label'=>$this->translate('admin-product-add-label-productserial'),'input'=>$product_serial),
					array('label'=>$this->translate('admin-product-add-label-price'),'input'=>$price),
					array('label'=>$this->translate('admin-product-add-label-productdetail'),'input'=>$product_detail),
					array('label'=>$this->translate('admin-product-add-label-coverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-product-add-label-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-product-add-label-lockstatus'),'input'=>$lock_status),

					array('label'=>$this->translate('admin-product-add-label-product_assessment'),'input'=>$product_assessment),					
					array('label'=>$this->translate('admin-product-add-label-product_guarantee'),'input'=>$product_guarantee),					
					array('label'=>$this->translate('admin-product-add-label-product_model'),'input'=>$product_model),
					array('label'=>$this->translate('admin-product-add-label-product_code'),'input'=>$product_code),
					array('label'=>$this->translate('admin-product-add-label-product_guarantee_policy'),'input'=>$product_guarantee_policy),
					array('label'=>$this->translate('admin-product-add-label-product_price_new'),'input'=>$product_price_new),
					array('label'=>$this->translate('admin-product-add-label-view_counter'),'input'=>$view_counter),
					
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-product/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-product/sublink/index.php'); ?>

	<?php
		if(!empty($errors)) {
	?>
		<div class="alert alert-danger"><?php echo $errors; ?></div>
	<?php 
		}
	?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>