<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;

	if ($formdata == null) {
		$formdata['product_category_id'] = 0;
		$formdata['product_name'] = '';
		$formdata['product_serial'] = '';
		$formdata['price'] = '';
		$formdata['product_detail'] = '';
		$formdata['cover_image'] = '';
		$formdata['publish'] = 0;
		$formdata['lock_status'] = 0;
		$formdata['order'] = 0;
		$formdata['created_by'] = '';
		$formdata['created_time'] = '0000-00-00 00:00:00';
		$formdata['last_modified_by'] = '';
		$formdata['last_modified_time'] = '0000-00-00 00:00:00';
		$formdata['publish_by'] = '';
		$formdata['publish_time'] = '0000-00-00 00:00:00';
		$formdata['hit_counter'] = 0;

		$formdata['product_assessment'] = '';
		$formdata['product_guarantee'] = '';
		$formdata['product_model'] = '';
		$formdata['product_code'] = '';
		$formdata['product_guarantee_policy'] = '';
		$formdata['product_price_new'] = '';
		$formdata['view_counter'] = '';

	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$linkProCat	= $this->baseUrl('/admin/admin-product-category/info/id/' .$formdata['product_category_id']);
	$category_name		= '<a href="' . $linkProCat . '">' . $formdata['category_name'] . '</a>';
	
	$product_name 	= $formdata['product_name'];
	$product_serial	= $formdata['product_serial'];
	$price		 	= $formdata['price'];
	$product_detail = $formdata['product_detail'];
	
	$product_assessment = $formdata['product_assessment'];
	$product_guarantee = $formdata['product_guarantee'];
	$product_model = $formdata['product_model'];
	$product_code = $formdata['product_code'];
	$product_guarantee_policy = $formdata['product_guarantee_policy'];
	$product_price_new = $formdata['product_price_new'];
	$view_counter = $formdata['view_counter'];

	//----- CREATE: publish option --------------------------
	$publish		= $formdata['publish'];
	if ($publish == 0) {
		$publish = $this->translate('admin-cw-publish');
	} else {
		$publish = $this->translate('admin-cw-nopublish');
	}
	
	//----- CREATE: lock status option --------------------------
	$lock_status	= $formdata['lock_status'];
	if ($lock_status == 0) {
		$lock_status = $this->translate('admin-cw-unlock');
	} else {
		$lock_status = $this->translate('admin-cw-lock');
	}
	
	$order 	= $formdata['order'];
	
	//----- CREATE: cover image option --------------------------
	$cover_image 	= FILES_URL . '/products/cover-images/small/' . $formdata['cover_image'];
	$cover_image	= '<img src="' . $cover_image .'"/><br/>';
	
	$created_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['created_id']) . '">' . $formdata['created_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$created_time	= date('d/m/Y H:i:s',strtotime($formdata['created_time']));
	
	$last_modified_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['last_modified_id']) . '">' . $formdata['last_modified_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$last_modified_time	= date('d/m/Y H:i:s',strtotime($formdata['last_modified_time']));
	
	//----- thong tin nguoi publish, ngay gio publish
	if ($formdata['publisher_id'] != 0) {
		$publisher_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['publisher_id']) . '">' . $formdata['publisher_name'] . '</a>';
		$publish_time	= date('d/m/Y H:i:s',strtotime($formdata['publish_time']));
	} else {
		$publisher_name	= '';
		$publish_time	= '';
	}
	
	$arrInput = array(
			array('label'=>$this->translate('admin-product-add-label-categoryname'),'input'=>$category_name),
			array('label'=>$this->translate('admin-product-add-label-productname'),'input'=>$product_name,'style'=>'font-size: 15pt;'),
			array('label'=>$this->translate('admin-product-add-label-productserial'),'input'=>$product_serial),
			array('label'=>$this->translate('admin-product-add-label-price'),'input'=>$price),
			array('label'=>$this->translate('admin-product-add-label-productdetail'),'input'=>$product_detail),
			array('label'=>$this->translate('admin-product-add-label-coverimage'),'input'=>$cover_image),
			array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
			array('label'=>$this->translate('admin-product-add-label-publish'),'input'=>$publish),
			array('label'=>$this->translate('admin-product-add-label-lockstatus'),'input'=>$lock_status),
			array('label'=>$this->translate('admin-cp-createdby'),'input'=>$created_name),
			array('label'=>$this->translate('admin-cp-createdtime'),'input'=>$created_time),
			array('label'=>$this->translate('admin-cp-lastmodifiedby'),'input'=>$last_modified_name),
			array('label'=>$this->translate('admin-cp-lastmodifiedtime'),'input'=>$last_modified_time),
			array('label'=>$this->translate('admin-cp-publishedby'),'input'=>$publisher_name),
			array('label'=>$this->translate('admin-cp-publishedtime'),'input'=>$publish_time),

		array('label'=>$this->translate('admin-product-add-label-product_assessment'),'input'=>$product_assessment),					
		array('label'=>$this->translate('admin-product-add-label-product_guarantee'),'input'=>$product_guarantee)	,				
		array('label'=>$this->translate('admin-product-add-label-product_model'),'input'=>$product_model),
		array('label'=>$this->translate('admin-product-add-label-product_code'),'input'=>$product_code),
array('label'=>$this->translate('admin-product-add-label-product_guarantee_policy'),'input'=>$product_guarantee_policy),
			array('label'=>$this->translate('admin-product-add-label-product_price_new'),'input'=>$product_price_new),
			array('label'=>$this->translate('admin-product-add-label-view_counter'),'input'=>$view_counter),
					
	);
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-product/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-product/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>