<form role="form" name="appForm" method="post" action="" autocomplete="off">
	<fieldset>
		<?php 
			$errors = '';
			if (count($this->messageError) > 0) {
				$errors = $this->formErrors($this->messageError, array('id'=>'errors'));
		?>
			<div class="form-group alert alert-danger">
				<?php echo $errors; ?>
			</div>
		<?php
			}
		?>
		
		<div class="form-group">
			<?php echo $this->formText('username','',array('class'=>'form-control','placeholder'=>'username','type'=>'username','autofocus'=>true)); ?>
		</div>
		
		<div class="form-group">
			<?php echo $this->formPassword('password','',array('class'=>'form-control','placeholder'=>'password','type'=>'password')); ?>
		</div>
		
		<div class="form-group">
			<?php echo $this->formText('captcha','',array('class'=>'form-control','placeholder'=>'enter captcha code')); ?>
		</div>
		
		<div class="form-group thumbnail">
			<?php echo $this->captcha; ?>
		</div>
		<?php echo $this->formHidden('captcha_id',$this->captcha_id); ?>
		<?php echo $this->formSubmit('submit','LOGIN',array('class'=>'btn btn-success')); ?>
	</fieldset>
</form>