<?php
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError, array('id'=>'errors'));
	}
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/public/toolbar/index.php'); ?>
	<div class="clr"></div>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				<div class="adminheader">Detail</div>
				<?php echo $errors; ?>
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>