<?php
//----- INPUT ELEMENT ---------------------------------------
//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
$formdata = $this->FormData;
$formstyle = $this->FormStyle;
if ($formdata == null) {
	$formdata['link_name'] ='';
	$formdata['url'] = '';

} else {
	$formdata = $this->cmsReplaceString($formdata);
}

//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
if ($formstyle == null) {
	$formstyle['link_name'] = '';
	$formstyle['url'] = '';
}


$menu_name 	= $this->formText('link_name',$formdata['link_name'],array('class'=>'form-control','style'=>$formstyle['link_name']));
$link 	= $this->formText('url',$formdata['url'],array('class'=>'form-control','style'=>$formstyle['url'],'disabled'=>true));


$arrInput = array(
		array('label'=>'Tên menu ','input'=>$menu_name),
		array('label'=> 'URL link','input'=>$link),
			
);

//----- thong bao loi -----
$errors = '';
if (count($this->messageError) > 0) {
	$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
}


?>

<form
	name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-news-article/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-news-article/sublink/index.php'); ?>

	<?php
	if(!empty($errors)) {
	?>
	<div class="alert alert-danger">
		<?php echo $errors; ?>
	</div>
	<?php 
		}
		?>

	<!--------------------------------------- BEGIN: CONTENT ---------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

			<!--------------------------------------- form add group ---------------------------------->
			<div id="adminfieldset">

				<?php echo $this->partialLoop('row.php',$arrInput); ?>

			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT -------------------->
</form>
