<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-page-edit-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null || empty($formdata)) {
		$formdata['page_title'] = '';
		$formdata['page_brief'] = '';
		$formdata['page_content'] = '';
		$formdata['cover_image'] = '';
		$formdata['current_cover_image'] = '';
		$formdata['publish'] = 1;
		$formdata['lock_status'] = 1;
		$formdata['order'] = 0;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}

	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null || empty($formstyle)) {
		$formstyle['page_title'] = '';
		$formstyle['page_brief'] = '';
		$formstyle['page_content'] = '';
		$formstyle['cover_image'] = 'width: 300px;';
		$formstyle['order'] = '';
	}	
	
	$page_title 	= $this->formText('page_title',$formdata['page_title'],array('class'=>'form-control','style'=>$formstyle['page_title']));
	$page_brief 	= $this->formText('page_brief',$formdata['page_brief'],array('class'=>'form-control','style'=>$formstyle['page_brief']));
	$page_content 	= $this->cmsEditor('page_content',$formdata['page_content'],array('toolbar'=>'FullToolbar'),array('class'=>'form-control'));
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-pages_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->Item['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-pages-add-publish-warning') . $this->formHidden('publish',0);
	}
	
	//----- CREATE: lock option ---------------------
	//----- lay du lieu cap phep cua nguoi dung login de xac dinh nguoi dung nay 
	//----- co quyen lock/unlock page hay khong
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-pages_change-lock-status', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->FormData['lock_status'] = 1;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-pages-add-warning') . $this->formHidden('lock_status',0);
	}
	
	$order 	= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	
	//----- CREATE: cover image option --------------------------
	if (!empty($formdata['cover_image'])) {
		$cover_image 	= FILES_URL . '/pages/cover-images/medium/' . $formdata['cover_image'];
		$cover_image	= '<img src="' . $cover_image .'"/><br/>';
		$current_cover_image = $this->formHidden('current_cover_image',$formdata['cover_image']);
	} else {
		$cover_image	= FILES_URL . '/pages/cover-images/medium/' . $formdata['current_cover_image'];
		$cover_image	= '<img src="' . $cover_image .'"/><br/>';
		$current_cover_image = $this->formHidden('current_cover_image',$formdata['current_cover_image']);
	}
	$imageSize = $this->imageSize('production','page_cover_image');
	$strRecommendSize = ' (recommend image size: ' .$imageSize['width'] .'px-' .$imageSize['height'] .'px)';
	$cover_image   .= $this->formFile('cover_image',array('style'=>'')) . $this->translate('admin-cp-uploadnewcoverimage')
										. '<br/>'. $strRecommendSize . $current_cover_image;
	
	$arrInput = array(
					array('label'=>$this->translate('admin-pages-add-label-pagetitle'),'input'=>$page_title),
					array('label'=>$this->translate('admin-pages-add-label-pagebrief'),'input'=>$page_brief),
					array('label'=>$this->translate('admin-pages-add-label-pagecontent'),'input'=>$page_content),
					array('label'=>$this->translate('admin-pages-add-label-pagecoverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-pages-add-label-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-pages-add-label-pagelockstatus'),'input'=>$lock_status),		
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-pages/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-pages/sublink/index.php'); ?>

	<?php
		if(!empty($errors)) {
	?>
		<div class="alert alert-danger"><?php echo $errors; ?></div>
	<?php 
		}
	?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
	<?php echo $this->render('/admin-pages/toolbar/index.php'); ?>
</form>