<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;

	if ($formdata == null) {
		$formdata['page_title'] = '';
		$formdata['page_brief'] = '';
		$formdata['page_content'] = '';
		$formdata['cover_image'] = '';
		$formdata['lock_status'] = 0;
		$formdata['order'] = 0;
		$formdata['user_id'] = 0;
		$formdata['user_name'] = '';
		$formdata['created_id'] = 0;
		$formdata['created_time'] = '0000-00-00 00:00:00';
		$formdata['last_modified_id'] = 0;
		$formdata['last_modified_time'] = '0000-00-00 00:00:00';
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}

	$page_title 	= $formdata['page_title'];
	$page_brief 	= $formdata['page_brief'];
	$page_content 	= $formdata['page_content'];
	$lock_status	= $formdata['lock_status'];
	if ($lock_status == 0) {
		$lock_status = $this->translate('admin-cw-unlock');
	} else {
		$lock_status = $this->translate('admin-cw-lock');
	}
	$order 	= $formdata['order'];
	
	//----- CREATE: cover image option --------------------------
	$cover_image 	= FILES_URL . '/pages/cover-images/medium/' . $formdata['cover_image'];
	$cover_image	= '<img src="' . $cover_image .'"/><br/>';
	
	$created_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['user_id']) . '">' . $formdata['user_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$created_time	= date('d/m/Y H:i:s',strtotime($formdata['created_time']));
	
	$last_modified_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['last_modified_id']) . '">' . $formdata['last_modified_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$last_modified_time	= date('d/m/Y H:i:s',strtotime($formdata['last_modified_time']));
	
	$arrInput = array(
					array('label'=>$this->translate('admin-pages-add-label-pagetitle'),'input'=>$page_title),
					array('label'=>$this->translate('admin-pages-add-label-pagebrief'),'input'=>$page_brief),
					array('label'=>$this->translate('admin-pages-add-label-pagecontent'),'input'=>$page_content),
					array('label'=>$this->translate('admin-pages-add-label-pagecoverimage'),'input'=>$cover_image),
					array('label'=>$this->translate('admin-pages-add-label-pagelockstatus'),'input'=>$lock_status),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-cp-createdby'),'input'=>$created_name),
					array('label'=>$this->translate('admin-cp-createdtime'),'input'=>$created_time),
					array('label'=>$this->translate('admin-cp-lastmodifiedby'),'input'=>$last_modified_name),
					array('label'=>$this->translate('admin-cp-lastmodifiedtime'),'input'=>$last_modified_time),
			);
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-pages/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-pages/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>