<?php 
	$user_name 	= $this->cmsReplaceString($this->Item['user_name']);
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-user/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-user/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors" class="alert alert-danger">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row" class="row">
					<div class="col-lg-12">
						<strong>Username: <span style="font-size: 15pt;"><?php echo $user_name; ?></span></strong>
					</div>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>