<?php
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblUsername = $this->cmsSortLink('u.user_name',$this->arrParam,$this->translate('admin-adminuser-col-username'),$this->imgUrl,$action_link);
	$lblUserID = $this->cmsSortLink('u.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblUserStatus = $this->cmsSortLink('u.status',$this->arrParam,$this->translate('admin-adminuser-col-status'),$this->imgUrl,$action_link);
	$lblUserEmail = $this->cmsSortLink('u.email',$this->arrParam,$this->translate('admin-adminuser-col-email'),$this->imgUrl,$action_link);
	$lblUserRegDate = $this->cmsSortLink('u.register_date',$this->arrParam,$this->translate('admin-adminuser-col-regdate'),$this->imgUrl,$action_link);
	$lblUserGroup = $this->cmsSortLink('g.group_name',$this->arrParam,$this->translate('admin-adminuser-col-group'),$this->imgUrl,$action_link);
	
	//--------------------------------------- CREATE: GROUP SELECT BOX --------------------------
	$options = $this->slbGroup;
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/group');
	$slbGroup = $this->formSelect('group_id',$ssFilter['group_id'],
							array('onchange'=>"OnSubmitForm('" .$linkSearch ."')"),$options);
	$selectGroup = 'Group: ' . $slbGroup;
	
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$keywords 		= $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch 	= $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch 		= $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-user/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-user/sublink/index.php'); ?>
	
	<!-- ------------------------------------ table Admin verion 2 ------------------------- -->
	<div class="panel panel-default adminlist">
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover" id="dataTables-object">
					<thead>
						<tr>
							<th class="col_cid">
								<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
							</th>
							<th><?php echo $this->translate('admin-adminuser-col-username'); ?></th>
							<th class="col_email" title='Email'><?php echo $this->translate('admin-adminuser-col-email'); ?></th>
							<th class="col_group_name"><?php echo $this->translate('admin-adminuser-col-group'); ?></th>
							<th class="col_status" title='Trạng thái'><?php echo $this->translate('admin-adminuser-col-status'); ?></th>
							<th class="col_register_time"><?php echo $this->translate('admin-adminuser-col-regdate'); ?></th>	
							<th class="col_control">Control</th>
						</tr>
					</thead>
					<tbody>
                                    
					<?php 
						foreach ($this->Items as $key => $value) {
							$value = $this->cmsReplaceString($value);
							$id = $value['id'];
							$user_name = $value['user_name'];
							$status = $value['status'];
							$email = $value['email'];
							$regdate = $value['register_date'];
							$group_name = $value['group_name'];
							if ($status == 1) {
								$linkStatus = $this->baseUrl($this->currentController .'/change-status/type/inactive/id/' .$id);
								$status = $this->cmsIconButton('Active','fa fa-hover fa-check',$linkStatus,'css');
							} else {
								$linkStatus = $this->baseUrl($this->currentController .'/change-status/type/active/id/' .$id);
								$status = $this->cmsIconButton('Inactive','fa fa-hover fa-minus-circle',$linkStatus,'css');
							}
							$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
							$btnInfo = $this->cmsIconButton('View information','fa fa-info-circle fa-lg',$linkInfo,'css');
							$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
							$btnEdit = $this->cmsIconButton('Edit Item','fa fa-edit fa-lg',$linkEdit,'css');
							$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
							$btnDelete = $this->cmsIconButton('Delete Item','fa fa-times-circle fa-lg',$linkDelete,'css');
							$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
							
							$cid = $this->formCheckbox('cid[]',$value['id']);
					?>
			
					
					<tr class="odd gradeX even">						
						<td align="center"><?php echo $cid; ?></td>
						<td align="left"><?php echo $user_name; ?></td>
						
						<td align="center"><?php echo $email; ?></td>
						
						<td align="center"><?php echo $group_name; ?></td>
						<td align="center"><?php echo $status; ?></td>
						<td align="center"><?php echo $regdate; ?></td>
						<td align="center"><?php echo $strControlIconButton; ?></td>
					</tr>
			
                <?php 
				} // ------------- dong vong lap foreach ----------------
			?>                    
                                        
					</tbody>
				</table>
			</div> <!-- /.table-responsive -->
		</div> <!-- /.panel-body -->
	</div>
	<!-- -------------------------------- End table Admin verion 2 ------------------------- -->	
</form>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-object').dataTable();
    });
</script>