<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-user/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-user/sublink/index.php'); ?>
	<?php 
		if (isset($this->cid)) {
			foreach ($this->cid as $key=>$val) {
				echo $this->formHidden('cid[]',$val); //----- de truyen nguoc lai trang multi-delete
			}
 			echo $this->formHidden('delConfirm',true); //----- de xac nhan du lieu nay duoc gui tu nut Accept
		}
	?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors" class="alert alert-danger">
					<?php echo $this->translate('admin-cp-confirm-multidelete'); ?>
				</div>
				
				<?php 
					foreach ($this->Items as $key=>$value) {
						$user_name = $this->cmsReplaceString($value['user_name']);
				?>
				<div id="row" class="delete-row">
					<strong>User Name:</strong>
					<span style="font-size: 15pt;"><?php echo $user_name; ?></span>
				</div><hr/>
				<?php
					}
				?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>