<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['category_name'] = '';
		$formdata['parent_category_id'] = 0;
		$formdata['description'] = '';
		$formdata['publish'] = 1;
		$formdata['lock_status'] = 1;
		$formdata['order'] = $this->lastServiceCatOrder + 1;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['category_name'] = '';
		$formstyle['order'] = '';
	}
	
	$category_name	= $this->formText('category_name',$formdata['category_name'],array('class'=>'form-control','style'=>$formstyle['category_name']));
	$order	 		= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	$description	= $this->formTextarea('description',$formdata['description'],array('cols'=>50,'rows'=>4));
	
	//--------------------------------------- CREATE: PARENT SERVICE CATEGORY SELECT BOX --------------------------
	$sourceArr = $this->slbServiceCat;
	$slbServiceCat = $this->cmsRecursiveSelectBox($sourceArr, array('parent'=>0,'level'=>1),
					array('name'=>'parent_category_id'));
	$selectCategory = $slbServiceCat;
	
	//----- CREATE: publish option --------------------------
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-service-category_publish', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-nopublish'),$this->translate('admin-cw-publish'));
		if (!isset($formdata['publish'])) {
			$this->Item['publish'] = 1;
		}
		$publish = $this->formRadio('publish',$formdata['publish'],null,$options, ' ');
	} else {
		$publish = $this->translate('admin-servicecategory-add-publish-warning') . $this->formHidden('publish',0);
	}
	
	//----- CREATE: lock option ---------------------
	//----- lay du lieu cap phep cua nguoi dung login de xac dinh nguoi dung nay
	//----- co quyen lock/unlock page hay khong
	$info = new Zend_Session_Namespace('info');
	if (!empty($info->acl['privileges'])) {
		$arrAcl = $info->acl['privileges'];
	} else {
		$arrAcl = array();
	}
	if (in_array('admin_admin-service-category_change-lock-status', $arrAcl) || $info->group['permission'] == 'Full Access') {
		$options = array($this->translate('admin-cw-unlock'),$this->translate('admin-cw-lock'));
		if (!isset($formdata['lock_status'])) {
			$this->FormData['lock_status'] = 1;
		}
		$lock_status = $this->formRadio('lock_status',$formdata['lock_status'],null,$options, ' ');
	} else {
		$lock_status = $this->translate('admin-servicecategory-add-lockstatus-warning') . $this->formHidden('lock_status',0);
	}
	
	$arrInput = array(
					array('label'=>$this->translate('admin-servicecategory-addform-label-categoryname'),'input'=>$category_name),
					array('label'=>$this->translate('admin-servicecategory-addform-label-parentcategory'),'input'=>$selectCategory),
					array('label'=>$this->translate('admin-cw-description'),'input'=>$description),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-servicecategory-addform-label-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-servicecategory-addform-label-lockstatus'),'input'=>$lock_status),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-service-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-service-category/sublink/index.php'); ?>

	<?php
		if(!empty($errors)) {
	?>
		<div class="alert alert-danger"><?php echo $errors; ?></div>
	<?php 
		}
	?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>