<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;
	
	$memberCount = $this->memberCount;
	$childCount = $this->childCount;

	if ($memberCount == 0) {
		$strMemberCount = $this->translate('admin-servicecategory-info-nonews');
	} else {
		$strMemberCount = '<span style="font-size: 15pt;">' .$memberCount .'</span>' . $this->translate('admin-servicecategory-info-havenews');
	}
	if ($childCount == 0) {
		$strChildCount = $this->translate('admin-servicecategory-info-nochild');
	} else {
		$strChildCount = '<span style="font-size: 15pt;">' .$childCount .'</span>' . $this->translate('admin-servicecategory-info-havechild');
	}
	
	if ($formdata == null) {
		$formdata['category_name'] = '';
		$formdata['description'] = 0;
		$formdata['publish'] = 1;
		$formdata['order'] = 1;
		$formdata['user_id'] = 0;
		$formdata['user_name'] = '';
		$formdata['created_id'] = 0;
		$formdata['created_name'] = '';
		$formdata['created_time'] = '0000-00-00 00:00:00';
		$formdata['last_modified_id'] = 0;
		$formdata['last_modified_name'] = '';
		$formdata['last_modified_time'] = '0000-00-00 00:00:00';
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$category_name 	= $formdata['category_name'];
	$description 	= $formdata['description'];
	$order			= $formdata['order'];
	
	$publish		= $formdata['publish'];
	if ($publish == 0) {
		$publish 	= $this->translate('admin-cw-nopublish');
	} else {
		$publish 	= $this->translate('admin-cw-publish');
	}
	
	$created_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['created_id']) . '">' . $formdata['created_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$created_time	= date('d/m/Y H:i:s',strtotime($formdata['created_time']));
	
	$last_modified_name	= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['last_modified_id']) . '">' . $formdata['last_modified_name'] . '</a>';
	//----- chuyen created time tu dang Y-m-d sang d-m-Y de hien thi ra view
	$last_modified_time	= date('d/m/Y H:i:s',strtotime($formdata['last_modified_time']));
	
	$arrInput = array(
					array('label'=>$this->translate('admin-servicecategory-col-categoryname'),'input'=>$category_name,'style'=>'font-size: 15pt;'),
					array('label'=>$this->translate('admin-cw-description'),'input'=>$description),
					array('label'=>$this->translate('admin-cw-publish'),'input'=>$publish),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-servicecategory-info-totaltour'),'input'=>$strMemberCount),
					array('label'=>$this->translate('admin-servicecategory-info-totalchild'),'input'=>$strChildCount),
					array('label'=>$this->translate('admin-cp-createdby'),'input'=>$created_name),
					array('label'=>$this->translate('admin-cp-createdtime'),'input'=>$created_time),
					array('label'=>$this->translate('admin-cp-lastmodifiedby'),'input'=>$last_modified_name),
					array('label'=>$this->translate('admin-cp-lastmodifiedtime'),'input'=>$last_modified_time),
			);	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-service-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-service-category/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>