<?php
	//----- kiem tra lock status. Neu trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	$lockStatus = $this->lockStatus;
	if ($lockStatus == 1) {
		$alertLockStatus = $this->translate('admin-newscategory-delete-lockalert');
		echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
	}

	$category_name 	= $this->cmsReplaceString($this->Item['category_name']);
	//----- thong bao loi -----
	$errors = '';
	$messageError = $this->messageError;
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-news-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-news-category/sublink/index.php'); ?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors" class="alert alert-danger">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row">
					News Category Name:
					<span style="font-size: 15pt;"><?php echo $category_name; ?>
						<?php if (!empty($messageError)) { ?>
							<div id = "errors" class="alert alert-danger" style="margin-top: 8px;">
								<?php echo $messageError; ?>
							</div>
						<?php } ?>
					</span>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>