<?php
	//----- kiem tra mang lock status. Neu ton tai 1 doi tuong trang thai bi khoa (lock_status == 1) thi canh bao
	//----- va redirect trang quay lai trang index
	if (isset($this->lockStatus) && !empty($this->lockStatus)) {
		$lockStatus = $this->lockStatus;
	} else {
		$lockStatus = array();
	}
	foreach ($lockStatus as $key=>$val) {
		if ($val['lock_status'] == 1) {
			$alertLockStatus = $this->translate('admin-newscategory-deletemulti-lockalert');
			echo "<script>alert('" . $alertLockStatus ."'); window.location = '" . $this->actionMain . "'</script>";
		}
	}

	//----- thong bao loi -----
	$errors = '';
	$messageError = $this->messageError;
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-news-category/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-news-category/sublink/index.php'); ?>
	<?php 
		if (isset($this->cid)) {
			foreach ($this->cid as $key=>$val) {
				echo $this->formHidden('cid[]',$val); //----- de truyen nguoc lai trang multi-delete
			}
 			echo $this->formHidden('delConfirm',true); //----- de xac nhan du lieu nay duoc gui tu nut Accept
		}
	?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors" class="alert alert-danger">
					<?php echo $this->translate('admin-cp-confirm-multidelete'); ?>
				</div>
				
				<?php 
					foreach ($this->Items as $key=>$value) {
						$category_id	= $value['id'];
						$category_name = $this->cmsReplaceString($value['category_name']);
				?>
				<div id="row" class="delete-row">
					<?php echo $this->translate('admin-newscategory-delform-label-categoryname'); ?>
					<span style="font-size: 15pt;"><?php echo $category_name; ?>
						<?php if (!empty($messageError[$category_id])) { ?>
							<div id = "errors" class="alert alert-danger" style="margin-top: 8px;">
								<?php echo $messageError[$category_id]; ?>
							</div>
						<?php } ?>
					</span>
				</div><hr/>
				<?php
					}
				?>
				
				
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>