<?php 
//var_dump($this->FormData);
//$param=$this->parram;?>
<div class="row">
	<div class="col-lg-12">
		<div id="toolbar-box">
			<div class="t">
				<div class="t">
					<div class="t"></div>
				</div>
			</div>
			
			<div class="m">
				
				<h3 class="page-header">System :: System setting :: List</h3>
		                                
				<div class="clr"></div>
			</div>
			<div class="b">
				<div class="b">
					<div class="b"></div>
				</div>
			</div>
		</div>
	</div>
</div>
	
	
	<div id="row" class="row page-header">
	<div class="col-lg-2">
		<strong>System setting</strong>
	</div>
	
		<?php 
		foreach ($this->FormData as $key => $row) {
			$name=$row['name'];
			$value=$row['value'];
			$id=$row['id'];
		?>
		<form name="appForm" method="post" action="" enctype="multipart/form-data">
		<div class="col-lg-4">
		<?php echo $name ;?> :<input type="text" name="arr[<?php echo $id;?>]" value=<?php echo $value;?> <br>
		</div>
		<div class="col-lg-6">
		<input type="submit" name="submit" value="Submit">
		</div>
		</form>
		<?php	
		}
		?>
		
	
	

</div>





