<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;

	if ($formdata == null) {
		$formdata['user_name'] = '';
		$formdata['group_id'] = '';
		$formdata['group_name'] = '';
		$formdata['user_avatar'] = '';
		$formdata['email'] = '';
		$formdata['first_name'] = '';
		$formdata['last_name'] = '';
		$formdata['birthday'] = '0000-00-00';
		$formdata['status'] = 1;
		$formdata['sign'] = '';
		$formdata['register_date'] = '0000-00-00';
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$linkGroupInfo	= $this->baseUrl('/admin/admin-group/info/id/' .$formdata['group_id']);	
	$group_name		= '<a href="' . $linkGroupInfo . '">' . $formdata['group_name'] . '</a>';
	$user_name 		= $formdata['user_name'];
	if (!empty($formdata['user_avatar'])) {
		$user_avatar 	= FILES_URL . '/users/user-avatar/small/' . $formdata['user_avatar'];
		$user_avatar	= '<img src="' . $user_avatar .'"/>';
	} else {
		$user_avatar	= '';
	}
	
	$email	 		= $formdata['email'];
	$first_name 	= $formdata['first_name'];
	$last_name 		= $formdata['last_name'];
	$birthday 		= $formdata['birthday'];
	//----- chuyen birthday tu dang Y-m-d sang d-m-Y de hien thi ra view
	$birthday = date('d-m-Y',strtotime($formdata['birthday']));
	
	$status			= $formdata['status'];
	if ($status == 0) {
		$status = $this->translate('admin-userinfo-inactive');
	} else {
		$status = $this->translate('admin-userinfo-active');
	}
	
	$register_date	= $formdata['register_date'];
	//----- chuyen register_date tu dang Y-m-d sang d-m-Y de hien thi ra view
	$register_date 	= date('d-m-Y',strtotime($formdata['register_date']));
	$sign			= $formdata['sign'];
	
	$arrInput = array(
					array('label'=>$this->translate('admin-adduser-addform-label-group'),'input'=>$group_name),
					array('label'=>$this->translate('admin-adduser-addform-label-username'),'input'=>$user_name,'style'=>'font-size: 15pt;'),
					array('label'=>$this->translate('admin-adduser-addform-label-avatar'),'input'=>$user_avatar),
					array('label'=>$this->translate('admin-adduser-addform-label-email'),'input'=>$email),
					array('label'=>$this->translate('admin-adduser-addform-label-firstname'),'input'=>$first_name),
					array('label'=>$this->translate('admin-adduser-addform-label-lastname'),'input'=>$last_name),
					array('label'=>$this->translate('admin-adduser-addform-label-birthday'),'input'=>$birthday),
					array('label'=>$this->translate('admin-adduser-addform-label-status'),'input'=>$status),
					array('label'=>$this->translate('admin-adduser-addform-label-registerdate'),'input'=>$register_date),
					array('label'=>$this->translate('admin-adduser-addform-label-sign'),'input'=>$sign),
			);	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-user/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-user/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>