<?php
	//----- INPUT ELEMENT ---------------------------------------
	//----- Lay du lieu truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao du lieu cho cac input cua form
	$formdata = $this->FormData;
	$formstyle = $this->FormStyle;
	if ($formdata == null) {
		$formdata['group_name'] = '';
		$formdata['parent_group_id'] = 0;
		$formdata['group_acp'] = 0;
		$formdata['permission'] = 1;
		$formdata['status'] = 1;
		$formdata['order'] = '';
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	//----- Lay dinh dang truyen tu controller sang dua vao cac input cua form
	//----- neu chua co thi tu khoi tao dinh dang cho cac input cua form
	if ($formstyle == null) {
		$formstyle['group_name'] = '';
		$formstyle['order'] = '';
	}
	
	$group_name		= $this->formText('group_name',$formdata['group_name'],array('class'=>'txtmedium','style'=>$formstyle['group_name']));
	$order	 		= $this->formText('order',$formdata['order'],array('class'=>'txtshort','style'=>$formstyle['order']));
	
	//--------------------------------------- CREATE: PARENT GROUP SELECT BOX --------------------------
	$options = $this->slbGroup;
	$slbGroup = $this->formSelect('parent_group_id',$formdata['parent_group_id'],null,$options);
	$selectGroup = 'Group: ' . $slbGroup;
	
	//----- CREATE: group_acp option --------------------------
	$options = array($this->translate('admin-cw-no'),$this->translate('admin-cw-yes'));
	$group_acp = $this->formRadio('group_acp',$formdata['group_acp'],null,$options, ' ');
	
	//----- CREATE: permission option --------------------------
	$options = array($this->translate('admin-cw-fullaccess'),$this->translate('admin-cw-limitaccess'));
	//$permission = $this->formRadio('permission',$formdata['permission'],null,$options, ' ');
	$permission = $this->formSelect('permission',1,null,$options);
	
	//----- CREATE: status option --------------------------
	$options = array($this->translate('admin-userinfo-inactive'),$this->translate('admin-userinfo-active'));
	$status = $this->formRadio('status',$formdata['status'],null,$options, ' ');
	
	
	$arrInput = array(
					array('label'=>$this->translate('admin-addgroup-addform-label-groupname'),'input'=>$group_name),
					array('label'=>$this->translate('admin-addgroup-addform-label-inherit'),'input'=>$slbGroup),
					array('label'=>$this->translate('admin-addgroup-addform-label-groupacp'),'input'=>$group_acp),
					array('label'=>$this->translate('admin-cw-permission'),'input'=>$permission),
					array('label'=>$this->translate('admin-addgroup-addform-label-status'),'input'=>$status),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
			);
	
	//----- thong bao loi -----
	$errors = '';
	if (count($this->messageError) > 0) {
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-group/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-group/sublink/index.php'); ?>

	<?php
		if(!empty($errors)) {
	?>
		<div class="alert alert-danger"><?php echo $errors; ?></div>
	<?php 
		}
	?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>