<?php 
	$group_name 	= $this->cmsReplaceString($this->Item['group_name']);
	//----- thong bao loi -----
	$errors = '';
	$messageError = $this->messageError;
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-group/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-group/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors" class="alert alert-danger">
					<?php echo $this->translate('admin-cp-confirm-delete'); ?>
				</div>
				
				<div id="row">
					<strong>Group Name:</strong>
					<span style="font-size: 15pt;"><?php echo $group_name; ?>
						<?php if (!empty($messageError)) { ?>
							<div id = "errors" class="alert alert-danger" style="margin-top: 8px;">
								<?php echo $messageError; ?>
							</div>
						<?php } ?>
					</span>
				</div>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>