<?php
	//--------------------------------------- CREATE: SEARCH AREA -------------------------------
	$ssFilter = $this->arrParam['ssFilter'];
	$action_link = $this->baseUrl($this->currentController . '/filter/type/order');
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	
	$btnSearch = $this->formButton('search-now','Search',
									array('onclick'=>"OnSubmitForm('" .$linkSearch ."');"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."');"));
	$strSearch = $keywords . ' ' . $btnSearch . ' ' .$btnResetSearch ;
	
	$curControllerLink = $this->baseUrl($this->currentController);
	$lblGroupName = $this->cmsSortLink('g.group_name',$this->arrParam,$this->translate('admin-admingroup-col-groupname'),$this->imgUrl,$action_link);
	$lblID = $this->cmsSortLink('g.id',$this->arrParam,'ID',$this->imgUrl,$action_link);
	$lblStatus = $this->cmsSortLink('g.status',$this->arrParam,$this->translate('admin-admingroup-col-status'),$this->imgUrl,$action_link);
	$lblAcp = $this->cmsSortLink('g.group_acp',$this->arrParam,$this->translate('admin-admingroup-col-acp'),$this->imgUrl,$action_link);
	$lblMembers = $this->cmsSortLink('members',$this->arrParam,$this->translate('admin-admingroup-col-members'),$this->imgUrl,$action_link);
	$lblOrder = $this->cmsSortLink('g.order',$this->arrParam,$this->translate('admin-admingroup-col-order'),$this->imgUrl,$action_link);
	
	
	//$linkOrderId = $this->cmsSortLink();
	
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-group/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-group/sublink/index.php'); ?>
	
	<!-- ------------------------------------ table Admin verion 2 ------------------------- -->
	<div class="panel panel-default adminlist">
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover" id="dataTables-object">
					<thead>
						<tr>
							<th width="43" >
								<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
							</th>
							<th><?php echo $this->translate('admin-admingroup-col-groupname'); ?></th>
							<th class="col_group_members"><?php echo $this->translate('admin-admingroup-col-members') ?></th>
							<th class="col_status" title='Trạng thái'><?php echo $this->translate('admin-admingroup-col-status'); ?></th>
							<th class="col_acp"><?php echo $this->translate('admin-admingroup-col-acp'); ?></th>
							<th class="col_order"><?php echo $this->translate('admin-admingroup-col-order'); ?></th>						
							<th class="col_control">Control</th></tr>
					</thead>
					<tbody>
                                    
					<?php 
						foreach ($this->Items as $key => $value) {
							$value = $this->cmsReplaceString($value);
							$id = $value['id'];
							$group_name = $value['group_name'];
							$status = $value['status'];
							if ($status == 1) {
								$linkStatus = $this->baseUrl($this->currentController .'/change-status/type/inactive/id/' .$id);
								$status = $this->cmsIconButton('Active','fa fa-hover fa-check',$linkStatus,'css');
							} else {
								$linkStatus = $this->baseUrl($this->currentController .'/change-status/type/active/id/' .$id);
								$status = $this->cmsIconButton('Inactive','fa fa-hover fa-minus-circle',$linkStatus,'css');
							}
							$group_acp = $value['group_acp'];
							if ($group_acp == 1) {
								$linkStatus = $this->baseUrl($this->currentController .'/change-acp/type/inactive/id/' .$id);
								$group_acp = $this->cmsIconButton('Allow access ACP','fa fa-hover fa-check',$linkStatus,'css');
							} else {
								$linkStatus = $this->baseUrl($this->currentController .'/change-acp/type/active/id/' .$id);
								$group_acp = $this->cmsIconButton('Deny access ACP','fa fa-hover fa-minus-circle',$linkStatus,'css');
							}
							$order = $value['order'];
							$order = $this->formText('order[' .$value['id'] .']',$value['order'],
												     array('style'=>'width: 30px; text-align: center;'));
							$members = $value['members'];
							$linkInfo = $this->baseUrl($this->currentController . '/info/id/' .$id);
							$btnInfo = $this->cmsIconButton('View information','fa fa-info-circle fa-lg',$linkInfo,'css');
							$linkEdit = $this->baseUrl($this->currentController . '/edit/id/' .$id);
							$btnEdit = $this->cmsIconButton('Edit Item','fa fa-edit fa-lg',$linkEdit,'css');
							$linkDelete = $this->baseUrl($this->currentController . '/delete/id/' .$id);
							$btnDelete = $this->cmsIconButton('Delete Item','fa fa-times-circle fa-lg',$linkDelete,'css');
							$strControlIconButton = $btnInfo . ' ' . $btnEdit . ' ' .$btnDelete;
							
							$cid = $this->formCheckbox('cid[]',$value['id']);
					?>
					
					<tr class="odd gradeX even">						
						<td align="center"><?php echo $cid; ?></td>
						<td align="left"><?php echo $group_name; ?></td>
						<td align="center"><?php echo $members; ?></td>
						<td align="center"><?php echo $status; ?></td>
						<td align="center"><?php echo $group_acp; ?></td>
						<td align="center"><?php echo $order; ?></td>
						<td align="center">
							<?php echo $strControlIconButton; ?>
						</td>
					</tr>
			
                <?php 
				} // ------------- dong vong lap foreach ----------------
			?>                    
                                        
					</tbody>
				</table>
			</div> <!-- /.table-responsive -->
		</div> <!-- /.panel-body -->
	</div>
	<!-- -------------------------------- End table Admin verion 2 ------------------------- -->
	
</form>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-object').dataTable();
    });
</script>
