<?php
	//----- Lay du lieu thong tin user truyen tu controller sang
	//----- neu chua co thi tu khoi tao du lieu thong tin user
	$formdata = $this->Item;
	$memberCount = $this->memberCount;
	$memberList = $this->memberList;
	$parent_group = $this->parent_group;
	if (!empty($parent_group)) {
		$parent_group_id = $parent_group['id'];
		$link = $this->baseUrl('/admin/admin-group/info/id/' . $parent_group_id);
		$parent_group_link = '<a href="' . $link . '">' . $parent_group['group_name'] . '</a>';
	} else {
		$parent_group_link = 'This group does not inherit from any group';
	} 
		

	if ($memberCount == null) {
		$memberCount = 0;
	}
	
	$linkMemberList = '';
	if (count($memberList) > 0) {
		//----- nhom co thanh vien
		$linkMemberList = $memberCount;
		foreach($memberList as $key=>$val) {
			$user_id = $val['id'];
			$user_name = $val['user_name'];
			$linkUserInfo = $this->baseUrl('/admin/admin-user/info/id/' .$user_id);
			$style = 'margin: 5px; padding: 1px 5px; background-color: #d8d8d8;';
			$linkMemberList .= '<a style="' . $style . '" href="' . $linkUserInfo . '">' . $user_name . '  ' . '</a>';		
		}
	} else {
		//----- nhom khong co thanh vien
		$linkMemberList = 'This group has no member';
	}
	if ($formdata == null) {
		$formdata['group_name'] = '';
		$formdata['group_acp'] = 0;
		$formdata['group_default'] = 1;
		$formdata['created'] = '';
		$formdata['created_by'] = '';
		//----- user_id va user_name cua user da tao ra group
		$formdata['user_id'] = 0;
		$formdata['user_name'] = '';
		$formdata['permission'] = '';
		$formdata['status'] = 1;
		$formdata['order'] = 1;
	} else {
		$formdata = $this->cmsReplaceString($formdata);
	}
	
	$group_name		= $formdata['group_name'];
	
	//----- chuyen group_acp tu so thanh chu
	$group_acp 		= $formdata['group_acp'];
	if ($group_acp == 1) {
		$group_acp = $this->translate('admin-cw-yes');
	} else if ($group_acp == 0) {
		$group_acp = $this->translate('admin-cw-no');
	}
	
	//----- chuyen group_default tu so thanh chu
	$group_default 	= $formdata['group_default'];
	if ($group_default == 1) {
		$group_default = $this->translate('admin-cw-yes');
	} else if ($group_default == 0) {
		$group_default = $this->translate('admin-cw-no');
	}
	
	//----- chuyen created tu dang Y-m-d sang d-m-Y de hien thi ra view
	$created 		= date('d-m-Y',strtotime($formdata['created']));
	$created_by		= '<a href="' .$this->baseUrl('/admin/admin-user/info/id/' .$formdata['user_id']) . '">' . $formdata['user_name'] . '</a>';
	$permission		= $formdata['permission'];
	$status			= $formdata['status'];
	if ($status == 0) {
		$status 	= $this->translate('admin-userinfo-inactive');
	} else {
		$status 	= $this->translate('admin-userinfo-active');
	}
	$order			= $formdata['order'];
	
	$arrInput = array(
					array('label'=>$this->translate('admin-addgroup-addform-label-groupname'),'input'=>$group_name,'style'=>'font-size: 15pt;'),
					array('label'=>$this->translate('admin-addgroup-addform-label-inherit'),'input'=>$parent_group_link,'style'=>'font-size: 11pt;'),
					array('label'=>$this->translate('admin-addgroup-addform-label-groupdefault'),'input'=>$group_default),
					array('label'=>$this->translate('admin-addgroup-addform-label-groupacp'),'input'=>$group_acp),
					array('label'=>$this->translate('admin-cw-permission'),'input'=>$permission),
					array('label'=>$this->translate('admin-addgroup-addform-label-status'),'input'=>$status),
					array('label'=>$this->translate('admin-cw-order'),'input'=>$order),
					array('label'=>$this->translate('admin-group-info-label-createddate'),'input'=>$created),
					array('label'=>$this->translate('admin-group-info-label-createdby'),'input'=>$created_by,'style'=>'font-size: 12pt;'),
					array('label'=>$this->translate('admin-group-info-label-membercount'),'input'=>$linkMemberList,'style'=>'font-size: 11pt;'),
			);	
	
?>

<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('/admin-group/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-group/sublink/index.php'); ?>
	
	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form add group ----------------------------------->
			<div id="adminfieldset">
				
				<?php echo $this->partialLoop('row.php',$arrInput); ?>
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>