<?php
	//----- thong bao loi -----
	$errors = '';
	$messageError = $this->messageError;
?>

<form name="appForm" method="post" action="">
	<?php echo $this->render('/admin-group/toolbar/index.php'); ?>
	<div class="clr"></div>
	<?php //echo $this->render('/admin-group/sublink/index.php'); ?>
	<?php 
		if (isset($this->cid)) {
			foreach ($this->cid as $key=>$val) {
				echo $this->formHidden('cid[]',$val); //----- de truyen nguoc lai trang multi-delete
			}
 			echo $this->formHidden('delConfirm',true); //----- de xac nhan du lieu nay duoc gui tu nut Accept
		}
	?>

	<!--------------------------------------- BEGIN: CONTENT ----------------------------------->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">

	<!--------------------------------------- form ----------------------------------->
			<div id="adminfieldset">
				
				<div id = "errors">
					<?php echo $this->translate('admin-cp-confirm-multidelete'); ?>
				</div>
				
				<?php 
					foreach ($this->Items as $key=>$value) {
						$group_id	= $value['id'];
						$group_name = $this->cmsReplaceString($value['group_name']);
				?>
				<div id="row" class="delete-row">
					<strong>Group Name:</strong>
					<span style="font-size: 15pt;"><?php echo $group_name; ?>
						<?php if (!empty($messageError[$group_id])) { ?>
							<div id = "errors" class="alert alert-danger" style="margin-top: 8px;">
								<?php echo $messageError[$group_id]; ?>
							</div>
						<?php } ?>
						
					</span>
					
				</div><hr/>
				<?php
					}
				?>
				
				
				
			</div>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!--------------------------------------- END: CONTENT ----------------------------------->
</form>